Repository MARS-LIKELION/NangPaGo, pull requests merged in 2024-12, with the labels that each got.

#8 chore(setup): Tailwind CSS와 Prettier 설정 추가
  NangPaGo-fe/.prettierrc
  NangPaGo-fe/eslint.config.js
  NangPaGo-fe/package-lock.json
  NangPaGo-fe/package.json
  NangPaGo-fe/postcss.config.js
  NangPaGo-fe/src/App.jsx
  NangPaGo-fe/src/index.css
  NangPaGo-fe/tailwind.config.js
  NangPaGo-fe/vite.config.js
Labels: enhancement

#22 NPG-40 release 브랜치로 PR 작성 시 CI 빌드 동작을 위한 script 수정
  .github/workflows/ci.yml
  PULL_REQUEST_TEMPLATE.md
Labels: bug, documentation

#23 NPG-41 JPA BaseEntity 작성
  NangPaGo-be/src/main/java/com/mars/NangPaGo/common/jpa/BaseEntity.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/config/JpaAuditingConfig.java
Labels: enhancement

#26 NPG-33 OAuth 로그인, 로그아웃 구현
  NangPaGo-be/build.gradle
  NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfiguration.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/config/WebConfig.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/auth/CustomSuccessHandler.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/controller/AuthController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/controller/UserController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/dto/RefreshDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/dto/UserRequestDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/dto/UserResponseDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/entity/Refresh.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/entity/User.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/enums/Gender.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/enums/Provider.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/factory/OAuth2UserInfoFactory.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/factory/userinfo/GoogleUserInfo.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/factory/userinfo/KakaoUserInfo.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/factory/userinfo/NaverUserInfo.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/factory/userinfo/OAuth2UserInfo.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/repository/RefreshTokenRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/repository/UserRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/service/CustomOAuth2UserService.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/service/RefreshTokenService.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/service/UserService.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/util/JwtFilter.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/util/JwtUtil.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/vos/CustomOAuth2User.java
  NangPaGo-be/src/main/resources/application.yml
  NangPaGo-fe/src/pages/login/LoginPage.jsx
  NangPaGo-fe/vite.config.js
Labels: enhancement

#27 [NPG-42] 레시피 리스트 페이지 구현
  NangPaGo-fe/index.html
  NangPaGo-fe/package-lock.json
  NangPaGo-fe/package.json
  NangPaGo-fe/src/App.jsx
  NangPaGo-fe/src/components/recipe/RecipeCard.jsx
  NangPaGo-fe/src/components/recipe/RecipeListContent.jsx
  NangPaGo-fe/src/components/recipe/RecipeListTab.jsx
  NangPaGo-fe/src/components/search/SearchBar.jsx
  NangPaGo-fe/src/main.jsx
  NangPaGo-fe/src/pages/Router.jsx
  NangPaGo-fe/src/pages/index.jsx
  NangPaGo-fe/src/pages/recipe/RecipeList.jsx
  NangPaGo-fe/src/pages/search/SearchPage.jsx
Labels: enhancement

#28 [NPG-30] DB 테이블 수정
  .gitignore
  NangPaGo-data/create_food_dict.py
Labels: chore

#30 [NPG-48] dockerfile 작성
  Dockerfile
  NangPaGo-be/.dockerignore
  NangPaGo-be/Dockerfile
  docker-compose.yml
Labels: enhancement

#35 NPG-58 개발환경 DB Connection pool 설정
  NangPaGo-be/src/main/resources/application.yml
Labels: bug, chore

#29 [NPG-45] 레시피 좋아요 토글 기능 추가
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/controller/RecipeController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/entity/RecipeLike.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/repository/RecipeLikeRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/service/RecipeLikeService.java
  NangPaGo-be/src/test/java/com/mars/NangPaGo/domain/recipe/repository/RecipeLikeRepositoryTest.java
Labels: enhancement

#41 [NO-ISSUE] Refresh token db 컬럼 순서 변경
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/dto/RefreshTokenDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/entity/RefreshToken.java
Labels: bug

#37 [NPG-46] ElasticSearch - 재료 사전 인덱스 삽입 (from CSV & from MySQL)
  NangPaGo-be/src/main/java/com/mars/NangPaGo/config/ElasticsearchConfig.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/controller/IngredientElasticController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/entity/Ingredient.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/entity/IngredientElastic.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/repository/IngredientElasticRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/repository/IngredientRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/service/IngredientElasticSynchronizer.java
Labels: enhancement

#42 [NO-ISSUE] ES build 관련 에러 해결
  NangPaGo-be/build.gradle
  NangPaGo-be/src/main/resources/application.yml
Labels: bug

#39 [NPG-60] CI 환경에서 통합 Test 제외
  .github/workflows/ci.yml
  NangPaGo-be/src/test/java/com/mars/NangPaGo/domain/recipe/repository/RecipeLikeRepositoryTest.java
Labels: bug

#43 [NO-ISSUE] fix(auth): 디비 저장할 때 토큰과 이메일 반대로 들어가는 버그 수정
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/auth/CustomSuccessHandler.java
Labels: bug

#46 [NPG-67] 토큰 재발급 URI 변경
  NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/controller/TokenController.java
  NangPaGo-fe/src/api/axiosInstance.js
Labels: chore

#47 [NPG-61] 레시피 상세페이지 API 구현
  NangPaGo-be/src/main/java/com/mars/NangPaGo/common/exception/NPGExceptionType.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/controller/RecipeController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/dto/RecipeRequestDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/dto/RecipeResponseDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/entity/Recipe.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/repository/ManualImageRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/repository/ManualRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/repository/RecipeRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/service/RecipeService.java
Labels: enhancement

#49 [NPG-69] 사용자 인증, 토큰 재발급 코드 리팩터링
  NangPaGo-be/src/main/java/com/mars/NangPaGo/common/exception/NPGExceptionType.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/controller/AuthController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/service/TokenService.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/service/UserService.java
  NangPaGo-fe/src/App.jsx
Labels: refactoring

#52 [NPG-61] 레시피 상세페이지 댓글 및 푸터 구현
  NangPaGo-fe/src/App.jsx
  NangPaGo-fe/src/api/axiosInstance.js
  NangPaGo-fe/src/components/common/Footer.jsx
  NangPaGo-fe/src/components/recipe/CookingSteps.jsx
  NangPaGo-fe/src/components/recipe/IngredientList.jsx
  NangPaGo-fe/src/components/recipe/Recipe.jsx
  NangPaGo-fe/src/pages/recipe/RecipeDetail.jsx
  NangPaGo-fe/src/pages/recipe/RecipeList.jsx
  NangPaGo-fe/src/slices/loginSlice.js
Labels: enhancement

#53 [NPG-46] 재료사전 search API 구현
  NangPaGo-be/src/main/java/com/mars/NangPaGo/common/exception/NPGExceptionType.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/controller/IngredientElasticController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/entity/Ingredient.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/entity/IngredientElastic.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/service/IngredientElasticSearchService.java
  NangPaGo-be/src/main/resources/elastic/ingredient/post-mapping.json
  NangPaGo-be/src/main/resources/elastic/ingredient/post-setting.json
Labels: enhancement

#50 [NPG-69] Token 관련 코드를 `jwt` 도메인 하위로 이전
  NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/jwt/controller/TokenController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/jwt/dto/RefreshTokenDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/jwt/entity/RefreshToken.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/jwt/repository/RefreshTokenRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/jwt/service/TokenService.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/jwt/util/JwtFilter.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/jwt/util/JwtUtil.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/auth/CustomSuccessHandler.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/service/CustomLogoutService.java
Labels: refactoring

#54 [NPG-70] Swagger UI 사용 환경 구축
  NangPaGo-be/build.gradle
  NangPaGo-be/gradle.properties
  NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SwaggerConfig.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/controller/RecipeController.java
  NangPaGo-be/src/main/resources/application.yml
Labels: enhancement

#56 [NPG-46] ElasticSearch Config 파일 삭제 & Swagger 적용
  NangPaGo-be/src/main/java/com/mars/NangPaGo/config/ElasticsearchConfig.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/controller/IngredientElasticController.java
Labels: chore

#57 [NPG-61] 레시피 댓글 api CRUD 구현
  NangPaGo-be/src/main/java/com/mars/NangPaGo/common/exception/NPGExceptionType.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/controller/RecipeCommentController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/dto/RecipeCommentRequestDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/dto/RecipeCommentResponseDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/entity/RecipeComment.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/repository/RecipeCommentRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/service/RecipeCommentService.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/entity/Recipe.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/entity/User.java
Labels: enhancement

#60 [NPG-61] 클라이언트에서 정상적으로 보내지만 서버에서 이메일이 null로 받는 버그 수정
  NangPaGo-fe/src/api/commentService.js
  NangPaGo-fe/src/components/recipe/comment/RecipeComment.jsx
Labels: bug

#62 [NPG-59] `/api` 접두어 추가, client-host 환경변수 처리
  NangPaGo-be/build.gradle
  NangPaGo-be/src/main/java/com/mars/NangPaGo/common/dto/ExampleResponseDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/controller/HomeController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/controller/RecipeCommentController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/controller/IngredientElasticController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/jwt/controller/TokenController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/controller/RecipeController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/auth/CustomSuccessHandler.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/controller/AuthController.java
  NangPaGo-be/src/main/resources/application.yml
  NangPaGo-fe/src/api/axiosInstance.js
  NangPaGo-fe/src/api/commentService.js
  NangPaGo-fe/src/pages/recipe/RecipeDetail.jsx
  NangPaGo-fe/src/slices/loginSlice.js
  NangPaGo-fe/vite.config.js
Labels: refactoring

#64 [NPG-61] [FE] 레시피 상세페이지 좋아요 구현
  NangPaGo-fe/src/components/recipe/Recipe.jsx
Labels: enhancement

#66 [NPG-71] 레시피 데이터 전처리 개선 (주요 대상: 재료목록)
  NangPaGo-data/create_ingredients_dictionary-legacy.py
  NangPaGo-data/create_recipes_cleaned.ipynb
Labels: enhancement

#65 [NPG-51] 레시피 검색 기능 구현
  NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/controller/RecipeController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/dto/RecipeEsResponseDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/entity/RecipeES.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/repository/RecipeESRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/service/RecipeEsService.java
Labels: enhancement

#63 [NPG-61] [BE] 레시피 상세페이지 좋아요 로직 수정
  NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/entity/RecipeComment.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/controller/RecipeController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/dto/RecipeEsResponseDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/dto/RecipeLikeRequestDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/dto/RecipeLikeResponseDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/entity/Recipe.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/entity/RecipeES.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/entity/RecipeLike.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/repository/RecipeLikeRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/service/RecipeEsService.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/service/RecipeLikeService.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/entity/User.java
Labels: enhancement

#68 [NPG-73] 레시피 좋아요 서버 엔드포인트에 맞춰 프론트 수정 및 댓글 페이징네이션 기능 추가
  NangPaGo-be/src/main/java/com/mars/NangPaGo/NangPaGoApplication.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/common/dto/PageDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/controller/RecipeCommentController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/repository/RecipeCommentRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/service/RecipeCommentService.java
  NangPaGo-fe/src/api/commentService.js
  NangPaGo-fe/src/components/recipe/CookingSteps.jsx
  NangPaGo-fe/src/components/recipe/Recipe.jsx
  NangPaGo-fe/src/components/recipe/comment/RecipeComment.jsx
Labels: refactoring

#70 [NPG-73] 레시피 즐겨찾기 기능 추가
  NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/controller/RecipeFavoriteController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/dto/RecipeFavoriteRequestDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/dto/RecipeFavoriteResponseDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/entity/RecipeFavorite.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/repository/RecipeFavoriteRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/service/RecipeFavoriteService.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/controller/RecipeController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/entity/Recipe.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/repository/RecipeLikeRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/service/RecipeLikeService.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/entity/User.java
  NangPaGo-fe/src/components/recipe/Recipe.jsx
Labels: enhancement, refactoring

#67 [NPG-59] API Server Port 설정을 환경변수로 주입받도록 변경
  NangPaGo-be/src/main/resources/application.yml
  NangPaGo-fe/Dockerfile
  NangPaGo-fe/index.html
  NangPaGo-fe/vite.config.js
  docker-compose.yml
Labels: chore

#74 [NPG-59] CI/CD on Github yml 작성
  .github/workflows/ci.yml
Labels: enhancement

#75 [NPG-75] 레시피 entity, dto 수정
  NangPaGo-be/src/main/java/com/mars/NangPaGo/common/exception/NPGExceptionType.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/dto/RecipeResponseDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/entity/Recipe.java
  NangPaGo-fe/src/components/recipe/Recipe.jsx
Labels: bug

#77 [NO-ISSUE] NangPago release/1.0.0 merge to main
  NangPaGo-be/src/main/java/com/mars/NangPaGo/common/exception/NPGExceptionType.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/dto/RecipeResponseDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/entity/Recipe.java
  NangPaGo-fe/src/components/recipe/Recipe.jsx
Labels: release

#78 [NPG-77] 소셜 Login redirection URL 버그 수정
  NangPaGo-fe/src/pages/login/Login.jsx
Labels: bug

#79 [NO-ISSUE] [NO-ISSUE] NangPago release/1.0.1 merge to main
  NangPaGo-be/gradle.properties
  NangPaGo-fe/src/pages/login/Login.jsx
Labels: release
