Repository MARS-LIKELION/NangPaGo, pull requests merged in 2025-02, with the labels that each got.

#276 [NO-ISSUE] 누락된 Service 레이어 테스트 코드 추가 작성
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/dto/RecipeFavoriteListResponseDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/controller/UserController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/service/UserService.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/comment/recipe/service/RecipeCommentServiceTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/community/service/CommunityServiceTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/recipe/service/RecipeLikeServiceTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/refrigerator/service/RefrigeratorServiceTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/user/service/UserServiceTest.java
Labels: refactoring, test

#277 [NO-ISSUE] 레시피 좋아요 SSE 관련 버그 수정, 리팩터링
  NangPaGo-admin/vite.config.js
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/controller/RecipeController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/event/RecipeLikeEvent.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/event/RecipeLikeEventListener.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/event/RecipeLikeNotificationConsumer.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/event/RecipeLikeNotificationPublisher.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/event/RecipeLikeSseService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/messaging/SseEmitterService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/service/RecipeLikeMessageService.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/recipe/event/RecipeLikeNotificationConsumerTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/recipe/event/RecipeLikeNotificationPublisherTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/recipe/service/RecipeLikeMessageServiceTest.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/sse/AbstractSseEmitterService.java
  NangPaGo-client/src/components/community/Community.jsx
  NangPaGo-client/src/components/recipe/Recipe.jsx
  NangPaGo-client/src/hooks/usePostStatus.js
Labels: bug, refactoring

#279 [NPG-206] 레시피 즐겨찾기 비동기로 개선
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/config/rabbitmq/RabbitMQConfig.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/controller/RecipeFavoriteController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/dto/RecipeFavoriteMessageDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/dto/RecipeFavoriteResponseDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/message/RecipeFavoriteMessageConsumer.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/message/RecipeFavoriteMessagePublisher.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/repository/RecipeFavoriteRepository.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/service/RecipeFavoriteService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/controller/RecipeController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/message/RecipeLikeMessageConsumer.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/message/RecipeLikeMessagePublisher.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/favorite/recipe/message/RecipeFavoriteMessageConsumerTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/favorite/recipe/message/RecipeFavoriteMessagePublisherTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/favorite/recipe/service/RecipeFavoriteServiceTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/recipe/message/RecipeLikeMessageConsumerTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/recipe/message/RecipeLikeMessagePublisherTest.java
  NangPaGo-client/src/api/postStatus.js
  NangPaGo-client/src/hooks/usePostStatus.js
Labels: refactoring

#281 [NO-ISSUE] Vite 6.x 버전 관련 이슈 해결
  NangPaGo-admin/vite.config.js
  NangPaGo-client/vite.config.js
Labels: bug

#283 [NPG-200] 마이페이지 게시글 탭 구현
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/dto/CommunityResponseDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/repository/CommunityRepository.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/controller/UserController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/service/UserService.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/community/service/CommunityServiceTest.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/dto/user/MyPageDto.java
  NangPaGo-client/src/api/myPage.js
  NangPaGo-client/src/components/profile/ItemList.jsx
  NangPaGo-client/src/components/profile/ProfileTabs.jsx
  NangPaGo-client/src/hooks/useMyPageInfo.js
  NangPaGo-client/src/hooks/useTabData.js
Labels: enhancement

#284 [NPG-218] 레시피 상세 - 조리과정 슬라이더 기능 및 UI 개선
  NangPaGo-client/src/components/button/SliderArrowButton.jsx
  NangPaGo-client/src/components/layout/header/Header.jsx
  NangPaGo-client/src/components/recipe/CookingStepsSlider.jsx
Labels: chore, refactoring

#274 [NPG-202] 관리자 유저 페이지 정렬 기능 추가
  NangPaGo-admin/src/api/usermanage.js
  NangPaGo-admin/src/pages/Users.jsx
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/controller/UserController.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/repository/UserRepository.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/service/UserService.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/sort/UserListSortType.java
  NangPaGo-api/NangPaGo-admin/src/test/java/com/mars/admin/domain/user/service/UserServiceTest.java
Labels: enhancement, test

#286 [NPG-163] 페이지네이션 공통 VO 구현
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/auth/entrypoint/UnauthorizedEntryPoint.java
  NangPaGo-api/NangPaGo-admin/src/test/java/com/mars/admin/domain/user/service/UserServiceTest.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/auth/entrypoint/UnauthorizedEntryPoint.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/community/controller/CommunityCommentController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/community/service/CommunityCommentService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/recipe/controller/RecipeCommentController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/recipe/service/RecipeCommentService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/controller/CommunityController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/service/CommunityService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/controller/RecipeFavoriteController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/service/RecipeFavoriteService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/controller/RecipeController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/service/RecipeEsService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/controller/UserController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/service/UserService.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/comment/community/service/CommunityCommentServiceTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/comment/recipe/service/RecipeCommentServiceTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/community/service/CommunityServiceTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/favorite/recipe/service/RecipeFavoriteServiceTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/user/service/UserServiceTest.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/dto/page/PageDto.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/dto/page/PageRequestVO.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/exception/NPGExceptionType.java
  NangPaGo-client/src/api/myPage.js
  NangPaGo-client/src/hooks/useTabData.js
  NangPaGo-client/src/pages/profile/Profile.jsx
Labels: refactoring

#287 [NO-ISSUE] 레시피 좋아요 SSE UI 업데이트 버그 픽스
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/auth/service/UserDetailServiceImpl.java
  NangPaGo-api/NangPaGo-admin/src/main/resources/application.yml
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/dto/RecipeLikeSseDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/event/RecipeLikeEventListener.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/event/RecipeLikeSseService.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/auth/handler/OAuth2SuccessHandlerTest.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/dto/user/UserResponseDto.java
  NangPaGo-client/src/hooks/usePostStatus.js
  NangPaGo-client/src/slices/loginSlice.js
Labels: bug

#285 [NPG-216] 리팩토링 - useMemo로 post 객체 생성
  NangPaGo-client/src/components/button/RecipeButton.jsx
  NangPaGo-client/src/components/common/ErrorGuidePage.jsx
  NangPaGo-client/src/components/community/Community.jsx
  NangPaGo-client/src/components/recipe/Recipe.jsx
  NangPaGo-client/src/hooks/usePostStatus.js
  NangPaGo-client/src/pages/common/DetailPage.jsx
  NangPaGo-client/src/pages/error/LoginExpired.jsx
  NangPaGo-client/src/pages/error/NotFound.jsx
  NangPaGo-client/src/pages/error/UnauthenticatedAccess.jsx
Labels: refactoring

#289 [NO-ISSUE] FIX - 레시피 리다이렉트 경로 버그 수정
  NangPaGo-client/src/pages/common/DetailPage.jsx
Labels: bug

#290 [NPG-163] 댓글 페이지네이션 공통 VO 적용
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/community/controller/CommunityCommentController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/community/repository/CommunityCommentRepository.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/community/service/CommunityCommentService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/recipe/controller/RecipeCommentController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/recipe/repository/RecipeCommentRepository.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/recipe/service/RecipeCommentService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/controller/CommunityController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/repository/CommunityRepository.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/service/CommunityService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/controller/RecipeFavoriteController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/controller/RecipeController.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/comment/community/service/CommunityCommentServiceTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/comment/recipe/service/RecipeCommentServiceTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/community/service/CommunityServiceTest.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/dto/page/PageRequestVO.java
  NangPaGo-client/src/api/comment.js
  NangPaGo-client/src/api/community.js
  NangPaGo-client/src/api/post.js
  NangPaGo-client/src/components/comment/Comment.jsx
  NangPaGo-client/src/components/comment/CommentList.jsx
  NangPaGo-client/src/hooks/useCommentsData.js
Labels: refactoring

#291 [NO-ISSUE] PageDto 클래스명 변경
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/community/controller/CommunityCommentController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/community/service/CommunityCommentService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/recipe/controller/RecipeCommentController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/recipe/service/RecipeCommentService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/controller/CommunityController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/service/CommunityService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/controller/RecipeFavoriteController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/service/RecipeFavoriteService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/controller/UserController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/service/UserService.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/comment/community/service/CommunityCommentServiceTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/comment/recipe/service/RecipeCommentServiceTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/community/service/CommunityServiceTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/favorite/recipe/service/RecipeFavoriteServiceTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/user/service/UserServiceTest.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/dto/page/PageResponseDto.java
Labels: chore

#292 [NPG-217] 브라우저에서 지원하는 기본 폰트로 변경
  NangPaGo-client/src/components/button/SocialLoginButton.jsx
  NangPaGo-client/src/globals.css
  NangPaGo-client/tailwind.config.js
Labels: chore

#293 [NO-ISSUE] UI 수정 - Header 아이콘 디자인 통일
  NangPaGo-client/src/components/layout/header/Header.jsx
  NangPaGo-client/src/components/layout/header/NavItem.jsx
Labels: chore

#296 [NO-ISSUE] 액세스 토큰 재발급 버그 픽스
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/auth/entrypoint/UnauthorizedEntryPoint.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/auth/entrypoint/UnauthorizedEntryPoint.java
Labels: bug

#297 [NO-ISSUE] NangPago release/1.8.1 merge to main
  NangPaGo-api/NangPaGo-admin/gradle.properties
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/auth/entrypoint/UnauthorizedEntryPoint.java
  NangPaGo-api/NangPaGo-app/gradle.properties
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/auth/entrypoint/UnauthorizedEntryPoint.java
Labels: release

#278 [NPG-179] 유저용 recipe 작성 community 백앤드 개발
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/userRecipe/controller/UserRecipeCommentController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/userRecipe/dto/UserRecipeCommentRequestDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/userRecipe/dto/UserRecipeCommentResponseDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/userRecipe/repository/UserRecipeCommentRepository.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/userRecipe/service/UserRecipeCommentService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/userRecipe/controller/UserRecipeController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/userRecipe/controller/UserRecipeLikeController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/userRecipe/dto/UserRecipeLikeResponseDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/userRecipe/dto/UserRecipeRequestDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/userRecipe/dto/UserRecipeResponseDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/userRecipe/repository/UserRecipeLikeRepository.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/userRecipe/repository/UserRecipeRepository.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/userRecipe/service/UserRecipeLikeService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/userRecipe/service/UserRecipeService.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/userRecipe/service/UserRecipeServiceTest.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/enums/comment/UserRecipeCommentStatus.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/enums/userRecipe/UserRecipeStatus.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/comment/userRecipe/UserRecipeComment.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/userRecipe/UserRecipe.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/userRecipe/UserRecipeIngredient.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/userRecipe/UserRecipeLike.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/userRecipe/UserRecipeManual.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/userRecipe/UserRecipeManualImage.java
Labels: enhancement

#299 [NPG-223] Admin - 파비콘, html title 변경
  NangPaGo-admin/index.html
  NangPaGo-admin/public/favicon.ico
  NangPaGo-admin/public/vite.svg
Labels: chore

#300 [NO-ISSUE] Mobile 사파리 화면 안열리는 버그 픽스 시도
  NangPaGo-client/package-lock.json
  NangPaGo-client/package.json
  NangPaGo-client/postcss.config.js
  NangPaGo-client/vite.config.js
Labels: bug

#298 [NPG-203] 어드민 페이지 유저 조회 필터 조건 추가
  NangPaGo-admin/src/api/usermanage.js
  NangPaGo-admin/src/pages/Users.jsx
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/controller/UserController.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/repository/UserRepository.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/service/UserService.java
  NangPaGo-api/NangPaGo-admin/src/test/java/com/mars/admin/domain/user/service/UserServiceTest.java
Labels: enhancement

#301 [NPG-225] 좋아요 및 즐겨찾기 아이콘 UI 변경
  NangPaGo-client/src/components/button/RecipeButton.jsx
  NangPaGo-client/src/components/community/Community.jsx
Labels: chore

#302 [NPG-212] 어드민 페이지 유저 조회 검색 기능 추가
  NangPaGo-admin/src/api/usermanage.js
  NangPaGo-admin/src/pages/Users.jsx
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/controller/UserController.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/enums/UserListSearchType.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/enums/UserListSortType.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/repository/UserRepository.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/service/UserService.java
  NangPaGo-api/NangPaGo-admin/src/test/java/com/mars/admin/domain/user/service/UserServiceTest.java
Labels: enhancement

#304 [NPG-227] MongoDB 개발 환경 구성, 감사 로그 저장 기능 추가
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/audit/repository/AuditLogRepository.java
  NangPaGo-api/NangPaGo-admin/src/main/resources/application.yml
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/aop/audit/AuditLog.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/aop/audit/AuditLogAspect.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/auth/handler/OAuth2SuccessHandler.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/config/common/JsonMessageConverter.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/config/rabbitmq/RabbitMQCommonConfig.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/config/rabbitmq/RabbitMQConfig.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/config/rabbitmq/impl/AuditLogRabbitConfig.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/config/rabbitmq/impl/RecipeFavoriteRabbitConfig.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/config/rabbitmq/impl/RecipeLikeRabbitConfig.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/audit/dto/AuditLogMessageDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/audit/message/AuditLogMessageConsumer.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/audit/message/AuditLogMessagePublisher.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/audit/repository/AuditLogRepository.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/community/controller/CommunityCommentController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/recipe/controller/RecipeCommentController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/controller/CommunityController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/message/RecipeFavoriteMessagePublisher.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/message/RecipeLikeMessagePublisher.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/controller/UserController.java
  NangPaGo-api/NangPaGo-app/src/main/resources/application.yml
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/audit/message/AuditLogMessageConsumerTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/audit/message/AuditLogMessagePublisherTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/favorite/recipe/message/RecipeFavoriteMessagePublisherTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/recipe/message/RecipeLikeMessagePublisherTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/support/config/TestTransactionConfig.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/enums/audit/AuditActionType.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/audit/AuditLog.java
  NangPaGo-api/build.gradle
  NangPaGo-client/src/api/post.js
  NangPaGo-client/src/components/common/Modal.jsx
  NangPaGo-client/src/pages/common/DetailPage.jsx
  NangPaGo-client/src/pages/community/ModifyCommunity.jsx
Labels: enhancement

#305 [NPG-208] 실시간 유저 알림 기능 구현
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/aop/auth/AuthenticationAspect.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/config/rabbitmq/impl/UserNotificationRabbitConfig.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/config/security/SecurityConfig.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/community/controller/CommunityCommentController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/controller/UserNotificationController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/dto/UserNotificationMessageDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/dto/UserNotificationSseDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/event/UserNotificationEvent.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/event/UserNotificationEventListener.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/event/UserNotificationSseService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/message/UserNotificationMessageConsumer.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/message/UserNotificationMessagePublisher.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/repository/UserNotificationRepository.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/aop/auth/AuthenticationAspectTest.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/enums/user/UserNotificationEventCode.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/exception/NPGExceptionType.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/user/UserNotification.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/util/web/JwtUtil.java
  NangPaGo-client/src/common/styles/Header.js
  NangPaGo-client/src/components/layout/header/Header.jsx
  NangPaGo-client/src/components/layout/header/NavItem.jsx
  NangPaGo-client/src/components/layout/header/ProfileDropdown.jsx
Labels: enhancement

#303 [NPG-226] 어드민 페이지 월별 작성 게시글 카운트 조회 기능 추가
  NangPaGo-admin/src/api/total.js
  NangPaGo-admin/src/pages/Home.jsx
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/community/repository/CommunityRepository.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/controller/DashboardController.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/service/ChartService.java
  NangPaGo-api/NangPaGo-admin/src/test/java/com/mars/admin/domain/dashboard/service/ChartServiceTest.java
Labels: enhancement

#306 [NPG-232] Admin 감사 로그 조회 기능 추가
  NangPaGo-admin/src/api/audit.js
  NangPaGo-admin/src/pages/Audit.jsx
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/config/swagger/SwaggerConfig.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/audit/controller/AuditLogController.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/audit/dto/AuditLogResponseDto.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/audit/repository/AuditLogRepository.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/audit/service/AuditLogService.java
Labels: enhancement

#307 [NPG-232] 감사 로그 기능 수정 - 로그 상세 정보 보기
  NangPaGo-admin/src/App.jsx
  NangPaGo-admin/src/api/audit.js
  NangPaGo-admin/src/components/DashboardLayout.jsx
  NangPaGo-admin/src/pages/Audit.jsx
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/audit/dto/AuditLogResponseDto.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/audit/service/AuditLogService.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/enums/audit/AuditActionType.java
Labels: enhancement

#309 [NPG-228] 유저 알림 UI 구현 (+ 헤더 UI 개선)
  NangPaGo-client/src/common/styles/Header.js
  NangPaGo-client/src/components/layout/header/Header.jsx
  NangPaGo-client/src/components/layout/header/NavItem.jsx
  NangPaGo-client/src/components/layout/header/ProfileDropdown.jsx
  NangPaGo-client/src/components/modal/LogoutModal.jsx
Labels: enhancement, refactoring

#311 [NO-ISSUE] 유저 알림 SSE 구독 - Access 토큰 예외 처리
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/controller/UserNotificationController.java
Labels: chore

#310 [NPG-224] Admin - 월별 회원가입 카운트 조회 기능 추가 및 통계 관련 API 통합
  NangPaGo-admin/src/api/total.js
  NangPaGo-admin/src/pages/Home.jsx
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/controller/DashboardController.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/dto/DashboardResponseDto.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/dto/MonthPostCountDto.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/dto/MonthRegisterCountDto.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/service/ChartService.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/repository/UserRepository.java
  NangPaGo-api/NangPaGo-admin/src/test/java/com/mars/admin/domain/dashboard/service/ChartServiceTest.java
Labels: enhancement, refactoring

#308 [NPG-219] user recipe 프론트앤드 구현
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/userRecipe/repository/UserRecipeCommentRepository.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/userRecipe/controller/UserRecipeController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/userRecipe/dto/UserRecipeRequestDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/userRecipe/dto/UserRecipeResponseDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/userRecipe/repository/UserRecipeRepository.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/userRecipe/service/UserRecipeService.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/userRecipe/service/UserRecipeServiceTest.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/userRecipe/UserRecipe.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/userRecipe/UserRecipeIngredient.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/userRecipe/UserRecipeManual.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/userRecipe/UserRecipeManualImage.java
  NangPaGo-client/package-lock.json
  NangPaGo-client/package.json
  NangPaGo-client/src/api/userRecipe.js
  NangPaGo-client/src/components/button/ToggleButton.jsx
  NangPaGo-client/src/components/community/Community.jsx
  NangPaGo-client/src/components/layout/header/Header.jsx
  NangPaGo-client/src/components/modal/DeleteSuccessModal.jsx
  NangPaGo-client/src/components/modal/FileSizeErrorModal.jsx
  NangPaGo-client/src/components/recipe/CookingStepsSlider.jsx
  NangPaGo-client/src/components/userRecipe/CookingStepCard.jsx
  NangPaGo-client/src/components/userRecipe/CookingSteps.jsx
  NangPaGo-client/src/components/userRecipe/CookingStepsSlider.jsx
  NangPaGo-client/src/components/userRecipe/FileUpload.jsx
  NangPaGo-client/src/components/userRecipe/IngredientInput.jsx
  NangPaGo-client/src/components/userRecipe/ManualInput.jsx
  NangPaGo-client/src/components/userRecipe/TextArea.jsx
  NangPaGo-client/src/components/userRecipe/TextInput.jsx
  NangPaGo-client/src/components/userRecipe/UserRecipeCard.jsx
  NangPaGo-client/src/components/userRecipe/UserRecipeDetail.jsx
  NangPaGo-client/src/components/userRecipe/UserRecipeListContent.jsx
  NangPaGo-client/src/pages/common/DetailPage.jsx
  NangPaGo-client/src/pages/common/ListPage.jsx
  NangPaGo-client/src/pages/community/CreateCommunity.jsx
  NangPaGo-client/src/pages/userRecipe/CreateUserRecipe.jsx
  NangPaGo-client/src/pages/userRecipe/ModifyUserRecipe.jsx
  NangPaGo-client/src/routes/Router.jsx
Labels: enhancement

#312 [NPG-235] 닉네임 변경 후 마이페이지로 리다이렉션
  NangPaGo-client/src/components/modal/UpdateUserInfoModal.jsx
Labels: chore

#313 [NPG-234] 내 냉장고(재료기반 레시피 조회)- 선택한 재료가 아닌 모든 재료로 조회되던 버그 수정
  NangPaGo-client/src/hooks/useRefrigerator.js
Labels: bug

#314 [NPG-233] 이미지가 아닌 다른 종류의 확장자 파일 업로드가 불가능하게 수정
  NangPaGo-client/src/components/common/Modal.jsx
  NangPaGo-client/src/components/community/FileUpload.jsx
  NangPaGo-client/src/components/modal/OnlyImageUploadModal.jsx
  NangPaGo-client/src/pages/community/ModifyCommunity.jsx
Labels: bug

#316 [NPG-237] 내 냉장고 무한스크롤 버그 수정
  NangPaGo-client/src/api/recipe.js
  NangPaGo-client/src/api/refrigerator.js
  NangPaGo-client/src/api/userRecipe.js
  NangPaGo-client/src/components/community/CommunityListContent.jsx
  NangPaGo-client/src/components/recipe/RecipeListContent.jsx
  NangPaGo-client/src/hooks/useRefrigerator.js
  NangPaGo-client/src/pages/refrigerator/Refrigerator.jsx
  NangPaGo-client/src/routes/AuthenticatedRoute.jsx
  NangPaGo-client/src/routes/Router.jsx
Labels: bug

#317 [NO-ISSUE] 전반적인 UI 개선 - `secondary` color 사용 지양
  NangPaGo-client/src/common/styles/ListPage.js
  NangPaGo-client/src/components/button/RecipeButton.jsx
  NangPaGo-client/src/components/community/Community.jsx
  NangPaGo-client/src/components/community/CommunityCard.jsx
  NangPaGo-client/src/components/profile/ItemList.jsx
  NangPaGo-client/src/components/recipe/Recipe.jsx
  NangPaGo-client/src/components/recipe/RecipeCard.jsx
  NangPaGo-client/src/components/recipe/RecipeInfo.jsx
  NangPaGo-client/src/components/recipe/RecipeListTab.jsx
  NangPaGo-client/src/components/refrigerator/IngredientList.jsx
  NangPaGo-client/src/components/search/SearchBar.jsx
  NangPaGo-client/src/components/search/SearchInput.jsx
  NangPaGo-client/src/components/userRecipe/UserRecipeCard.jsx
  NangPaGo-client/src/pages/search/RecipeSearch.jsx
  NangPaGo-client/src/pages/search/RefrigeratorSearch.jsx
Labels: chore

#318 [NO-ISSUE] 레시피 리스트 조회 응답에 '좋아요 여부' 추가
  NangPaGo-api/NangPaGo-admin/src/main/resources/application.yml
  NangPaGo-api/NangPaGo-admin/src/test/java/com/mars/admin/support/AbstractRepositoryTestSupport.java
  NangPaGo-api/NangPaGo-admin/src/test/java/com/mars/admin/support/extend/RepositoryTestCondition.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/controller/RecipeController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/controller/favorite/RecipeFavoriteController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/dto/RecipeEsResponseDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/dto/favorite/RecipeFavoriteListResponseDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/dto/favorite/RecipeFavoriteMessageDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/dto/favorite/RecipeFavoriteRequestDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/dto/favorite/RecipeFavoriteResponseDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/dto/like/RecipeLikeMessageDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/dto/like/RecipeLikeRequestDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/dto/like/RecipeLikeResponseDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/dto/like/RecipeLikeSseDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/event/RecipeLikeEventListener.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/event/RecipeLikeSseService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/message/favorite/RecipeFavoriteMessageConsumer.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/message/favorite/RecipeFavoriteMessagePublisher.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/message/like/RecipeLikeMessageConsumer.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/message/like/RecipeLikeMessagePublisher.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/repository/favorite/RecipeFavoriteRepository.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/repository/like/RecipeLikeRepository.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/service/RecipeEsService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/service/favorite/RecipeFavoriteService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/service/like/RecipeLikeService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/controller/UserController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/service/UserService.java
  NangPaGo-api/NangPaGo-app/src/main/resources/application.yml
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/favorite/recipe/message/RecipeFavoriteMessageConsumerTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/favorite/recipe/message/RecipeFavoriteMessagePublisherTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/favorite/recipe/service/RecipeFavoriteServiceTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/recipe/message/RecipeLikeMessageConsumerTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/recipe/message/RecipeLikeMessagePublisherTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/recipe/repository/RecipeLikeRepositoryTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/recipe/service/RecipeLikeServiceTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/user/service/UserServiceTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/support/AbstractRepositoryTestSupport.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/support/extend/RepositoryTestCondition.java
  NangPaGo-client/src/components/recipe/RecipeCard.jsx
Labels: enhancement, refactoring

#319 [NPG-240] 커뮤니티 게시글 좋아요 비동기 전환 및 SSE 구현
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/config/rabbitmq/impl/CommunityLikeRabbitConfig.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/config/security/SecurityConfig.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/controller/like/CommunityLikeController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/dto/CommunityLikeResponseDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/dto/like/CommunityLikeMessageDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/dto/like/CommunityLikeResponseDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/dto/like/CommunityLikeSseDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/event/CommunityLikeEvent.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/event/CommunityLikeEventListener.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/event/CommunityLikeSseService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/message/like/CommunityLikeMessageConsumer.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/message/like/CommunityLikeMessagePublisher.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/repository/CommunityLikeRepository.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/service/CommunityLikeService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/service/like/CommunityLikeService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/controller/RecipeController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/controller/like/RecipeLikeController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/dto/like/RecipeLikeRequestDto.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/community/message/like/CommunityLikeMessageConsumerTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/community/message/like/CommunityLikeMessagePublisherTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/community/service/CommunityLikeServiceTest.java
  NangPaGo-client/src/hooks/usePostStatus.js
Labels: enhancement, refactoring

#320 [NO-ISSUE] 좋아요 - 바운스 & 카운트 애니메이션 추가
  NangPaGo-client/src/components/button/RecipeButton.jsx
  NangPaGo-client/src/components/community/Community.jsx
  NangPaGo-client/tailwind.config.js
Labels: enhancement

#323 [NPG-241] 유저 알림 발행 포인트 추가
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/controller/CommunityLikeController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/message/like/CommunityLikeMessageConsumer.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/controller/UserNotificationController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/message/UserNotificationMessageConsumer.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/repository/UserNotificationRepository.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/service/UserNotificationService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user_recipe/controller/UserRecipeCommentController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user_recipe/controller/UserRecipeLikeController.java
  NangPaGo-client/src/api/notification.js
  NangPaGo-client/src/components/layout/header/ProfileDropdown.jsx
Labels: chore

#324 [NO-ISSUE] 유저 레시피 좋아요 비동기, SSE 구현
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/config/rabbitmq/impl/UserRecipeLikeRabbitConfig.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/config/security/SecurityConfig.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/dto/CommunityResponseDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/repository/CommunityLikeRepository.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/service/CommunityService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user_recipe/controller/UserRecipeLikeController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user_recipe/dto/UserRecipeLikeResponseDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user_recipe/dto/like/UserRecipeLikeMessageDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user_recipe/dto/like/UserRecipeLikeResponseDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user_recipe/dto/like/UserRecipeLikeSseDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user_recipe/event/UserRecipeLikeEvent.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user_recipe/event/UserRecipeLikeEventListener.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user_recipe/event/UserRecipeLikeSseService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user_recipe/message/UserRecipeLikeMessageConsumer.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user_recipe/message/UserRecipeLikeMessagePublisher.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user_recipe/service/UserRecipeLikeService.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/community/message/like/CommunityLikeMessageConsumerTest.java
  NangPaGo-client/src/components/community/CommunityCard.jsx
  NangPaGo-client/src/components/community/CommunityListContent.jsx
  NangPaGo-client/src/components/userRecipe/UserRecipeDetail.jsx
  NangPaGo-client/src/hooks/usePostStatus.js
Labels: enhancement

#326 [NPG-246] 관리자 페이지 그래프 최소 개수로 보이도록 개선
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/service/ChartService.java
  NangPaGo-api/NangPaGo-admin/src/test/java/com/mars/admin/domain/dashboard/service/ChartServiceTest.java
Labels: refactoring

#327 [NPG-243] 커뮤니티 & 유저 레시피 - 작성자 닉네임 추가
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user_recipe/dto/UserRecipeResponseDto.java
  NangPaGo-client/src/components/community/Community.jsx
  NangPaGo-client/src/components/userRecipe/UserRecipeDetail.jsx
Labels: chore

#328 [NO-ISSUE] 리팩토링 - 기존의 유저 레시피와 커뮤니티 공통화
  NangPaGo-client/src/api/community.js
  NangPaGo-client/src/api/post.js
  NangPaGo-client/src/api/userRecipe.js
  NangPaGo-client/src/components/common/Modal.jsx
  NangPaGo-client/src/components/community/Community.jsx
  NangPaGo-client/src/components/community/CommunityListContent.jsx
  NangPaGo-client/src/components/layout/header/Header.jsx
  NangPaGo-client/src/components/modal/DeletePostSuccessModal.jsx
  NangPaGo-client/src/components/modal/DeleteSuccessModal.jsx
  NangPaGo-client/src/components/userRecipe/UserRecipe.jsx
  NangPaGo-client/src/components/userRecipe/UserRecipeListContent.jsx
  NangPaGo-client/src/pages/common/DetailPage.jsx
  NangPaGo-client/src/pages/common/ListPage.jsx
  NangPaGo-client/src/pages/community/CreateCommunity.jsx
  NangPaGo-client/src/pages/userRecipe/ModifyUserRecipe.jsx
  NangPaGo-client/src/routes/Router.jsx
Labels: refactoring

#325 [NPG-213] 기존 레시피 이미지 압축 및 리사이징
  NangPaGo-api/NangPaGo-app/build.gradle
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/config/security/SecurityConfig.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/firebase/controller/FirebaseStorageController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/firebase/service/FirebaseOptimizeService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/firebase/service/FirebaseStorageService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/firebase/service/ImageOptimizationService.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/exception/NPGExceptionType.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/recipe/ManualImage.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/recipe/Recipe.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/userRecipe/UserRecipe.java
Labels: enhancement

#330 [NPG-244] BUGFIX - UserRecipe 좋아요 토글 중복 요청
  NangPaGo-client/src/components/button/PostStatusButton.jsx
  NangPaGo-client/src/components/button/RecipeButton.jsx
  NangPaGo-client/src/components/community/Community.jsx
  NangPaGo-client/src/components/recipe/Recipe.jsx
  NangPaGo-client/src/components/userRecipe/UserRecipe.jsx
Labels: bug, refactoring

#331 [NPG-230] 알림 클릭하여 바로가기
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/controller/UserNotificationController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/dto/UserNotificationCountResponseDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/dto/UserNotificationMessageDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/dto/UserNotificationResponseDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/message/UserNotificationMessageConsumer.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/repository/UserNotificationRepository.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/service/UserNotificationService.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/user/UserNotification.java
  NangPaGo-client/src/api/notification.js
  NangPaGo-client/src/common/styles/Header.js
  NangPaGo-client/src/components/layout/header/ProfileDropdown.jsx
Labels: enhancement, refactoring

#334 [NO-ISSUE] NangPago release/1.10.1 merge to main
  NangPaGo-api/NangPaGo-app/gradle.properties
Labels: release

#333 [NPG-242] 관리자 세션 방식으로 변경
  NangPaGo-admin/src/App.jsx
  NangPaGo-admin/src/api/axiosInstance.js
  NangPaGo-admin/src/components/common/AuthErrorPage.jsx
  NangPaGo-admin/src/components/common/Modal.jsx
  NangPaGo-admin/src/components/modal/AuthErrorModal.jsx
  NangPaGo-admin/tailwind.config.js
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/auth/handler/AdminSuccessHandler.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/auth/service/AdminLogoutSuccessHandler.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/config/security/SecurityConfig.java
Labels: refactoring

#335 [NO-ISSUE] 토글 버튼 (작성, 작성/수정/삭제) 아이콘 변경
  NangPaGo-client/src/components/button/ToggleButton.jsx
Labels: chore

#337 [NO-ISSUE] BUGFIX - 유저레시피 작성 시, firefox 업로드 과정 500에러 발생
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user_recipe/service/UserRecipeService.java
Labels: bug

#338 [NO-ISSUE] 레시피 검색어 폰트 색상 변경 및 mainImage 사이즈 조정
  NangPaGo-client/src/common/styles/Image.js
  NangPaGo-client/src/components/community/Community.jsx
  NangPaGo-client/src/components/layout/Footer.jsx
  NangPaGo-client/src/components/modal/BuildVersionModal.jsx
  NangPaGo-client/src/components/recipe/Recipe.jsx
  NangPaGo-client/src/components/recipe/RecipeImage.jsx
  NangPaGo-client/src/components/search/SearchBar.jsx
  NangPaGo-client/src/components/userRecipe/UserRecipe.jsx
Labels: chore

#340 [NO-ISSUE] Admin 세션 타임아웃 설정
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/config/security/SecurityConfig.java
  NangPaGo-api/NangPaGo-admin/src/main/resources/application.yml
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user_recipe/repository/UserRecipeLikeRepository.java
Labels: chore

#341 [NPG-252] 자기 자신의 게시글에 대한 활동에는 알림 발송 방지
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/message/UserNotificationMessageConsumer.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/user_recipe/service/UserRecipeServiceTest.java
Labels: chore

#342 [NO-ISSUE] 커뮤니티, 유저 레시피 네비게이션 버그 수정
  NangPaGo-client/src/components/common/ContentCard.jsx
  NangPaGo-client/src/components/community/CommunityListContent.jsx
Labels: bug

#343 [NPG-244] BUGFIX - 레시피 디테일 페이지 내 postStatus 중복 요청
  NangPaGo-client/src/components/recipe/Recipe.jsx
Labels: bug

#344 [NPG-254] 내 냉장고 재료 검색창 UI 개선
  NangPaGo-client/src/components/refrigerator/AddIngredientForm.jsx
Labels: chore

#329 [NPG-247] RecipeSearch Keyword검색시, Dto를 분리하여 최소값만 반환하도록 구현
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/config/security/SecurityConfig.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/controller/RecipeController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/dto/RecipeSearchResponseDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/service/RecipeEsService.java
  NangPaGo-client/src/api/recipe.js
  NangPaGo-client/src/components/community/CommunityListContent.jsx
  NangPaGo-client/src/components/recipe/RecipeListContent.jsx
  NangPaGo-client/src/components/search/SearchResult.jsx
  NangPaGo-client/src/components/userRecipe/UserRecipeListContent.jsx
  NangPaGo-client/src/hooks/useRecipeSearch.js
  NangPaGo-client/src/pages/refrigerator/Refrigerator.jsx
  NangPaGo-client/src/pages/search/RecipeSearch.jsx
Labels: enhancement

#345 [NPG-251] 개선: 상단 Tab 메뉴 개선 및 내냉장고 리스트 header 변경
  NangPaGo-client/src/components/layout/header/Header.jsx
  NangPaGo-client/src/components/layout/header/NavItem.jsx
  NangPaGo-client/src/components/layout/header/ProfileDropdown.jsx
  NangPaGo-client/src/pages/refrigerator/Refrigerator.jsx
Labels: chore

#347 [NPG-245] UI 개선 - 유저 레시피 상세 페이지
  NangPaGo-client/src/components/userRecipe/CookingStepCard.jsx
  NangPaGo-client/src/components/userRecipe/CookingSteps.jsx
  NangPaGo-client/src/components/userRecipe/CookingStepsSlider.jsx
  NangPaGo-client/src/components/userRecipe/UserRecipe.jsx
Labels: enhancement

#346 [NO-ISSUE] 냉장고에서 식재료 검색시, 렌더링 해오지 못하는 문제 해결
  NangPaGo-client/src/api/recipe.js
  NangPaGo-client/src/api/refrigerator.js
  NangPaGo-client/src/components/common/ContentCard.jsx
  NangPaGo-client/src/hooks/useRefrigerator.js
  NangPaGo-client/src/pages/refrigerator/Refrigerator.jsx
Labels: bug

#351 [NPG-213] 레시피 이미지 수정 및 삭제시 스토리지에서 이미지 삭제 기능 추가
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/NangPaGoApplication.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user_recipe/service/UserRecipeService.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/user_recipe/service/UserRecipeServiceTest.java
Labels: enhancement

#353 [NPG-259] Admin - 사용자관리 table의 생년월일, 전화번호 column 제거
  NangPaGo-admin/src/pages/Users.jsx
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/dto/UserDetailResponseDto.java
Labels: chore

#354 [NPG-254] 레시피 검색 이후 일부 검색 조건에 따라 X버튼 기능이 안되던 버그 수정
  NangPaGo-client/src/components/search/SearchBar.jsx
  NangPaGo-client/src/pages/common/ListPage.jsx
Labels: bug

#355 [NPG-258] Admin - 사용자 검색창 위치 및 버튼 색상 변경
  NangPaGo-admin/src/common/styles/CommonButton.js
  NangPaGo-admin/src/pages/Users.jsx
Labels: chore

#356 [NO-ISSUE] 냉장고 추천레시피에서 잘못된 api가 호출되던 문제 해결
  NangPaGo-client/src/hooks/useRefrigerator.js
Labels: bug

#357 [NO-ISSUE] Refrigerator 잘못된 api호출되던 현상
  NangPaGo-client/src/hooks/useRefrigerator.js
Labels: bug

#358 [NPG-256] 어드민 페이지 일일 접속자 수 통계 구현
  NangPaGo-admin/package-lock.json
  NangPaGo-admin/package.json
  NangPaGo-admin/src/pages/Dashboard.jsx
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/controller/DashboardController.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/dto/DailyUserStatsDto.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/dto/DashboardResponseDto.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/service/ChartService.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/stats/repository/VisitLogRepository.java
Labels: enhancement

#359 [NO-ISSUE] 배포 서버 SSE 이슈 원인 파악을 위한 로그 수집
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/dto/UserNotificationSseDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/event/UserNotificationEventListener.java
Labels: bug

#360 [NO-ISSUE] NangPago release/1.12.0 merge to main
  NangPaGo-admin/package-lock.json
  NangPaGo-admin/package.json
  NangPaGo-admin/src/common/styles/CommonButton.js
  NangPaGo-admin/src/pages/Dashboard.jsx
  NangPaGo-admin/src/pages/Users.jsx
  NangPaGo-api/NangPaGo-admin/gradle.properties
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/controller/DashboardController.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/dto/DailyUserStatsDto.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/dto/DashboardResponseDto.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/service/ChartService.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/stats/repository/VisitLogRepository.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/dto/UserDetailResponseDto.java
  NangPaGo-api/NangPaGo-app/gradle.properties
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/NangPaGoApplication.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/dto/CommunityRequestDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/firebase/service/FirebaseStorageService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/builder/EsRecipeSearchQueryBuilder.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/controller/RecipeController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/dto/RecipeSearchResponseDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/service/RecipeEsService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/dto/UserNotificationSseDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/event/UserNotificationEventListener.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user_recipe/controller/UserRecipeCommentController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user_recipe/controller/UserRecipeController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user_recipe/service/UserRecipeService.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/community/service/CommunityServiceTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/user_recipe/service/UserRecipeServiceTest.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/enums/audit/AuditActionType.java
  NangPaGo-client/src/api/recipe.js
  NangPaGo-client/src/components/recipe/RecipeListContent.jsx
  NangPaGo-client/src/components/search/SearchBar.jsx
  NangPaGo-client/src/hooks/useRefrigerator.js
  NangPaGo-client/src/pages/common/ListPage.jsx
Labels: release

#361 [NO-ISSUE] SSE 연결 로직 개선 (모니터링 필요)
  NangPaGo-client/src/components/layout/header/Header.jsx
Labels: refactoring

#362 [NPG-257] 어드민 페이지 - 시간대별 사용자 활동 분석 차트 구현
  NangPaGo-admin/src/pages/Dashboard.jsx
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/audit/repository/AuditLogRepository.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/controller/DashboardController.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/dto/DashboardResponseDto.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/dto/HourlyUserActionCountDto.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/service/ChartService.java
Labels: enhancement

#363 [NPG-261] Admin - 감사 로그에서 이메일 클릭 시 User 페이지로 바로 전환
  NangPaGo-admin/src/pages/Audit.jsx
  NangPaGo-admin/src/pages/Users.jsx
Labels: enhancement

#364 [NO-ISSUE] 유저 레시피 매뉴얼 이미지 업로드 버그 수정
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/firebase/service/FirebaseStorageService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user_recipe/service/UserRecipeService.java
  NangPaGo-api/NangPaGo-app/src/main/resources/application.yml
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/userRecipe/UserRecipe.java
  NangPaGo-client/src/components/userRecipe/ManualInput.jsx
  NangPaGo-client/src/pages/userRecipe/CreateUserRecipe.jsx
  NangPaGo-client/src/pages/userRecipe/ModifyUserRecipe.jsx
Labels: bug

#365 [NO-ISSUE] 냉장고 레시피 추천 - 상세 페이지 접속 후 뒤로 돌아올때 검색결과 초기화되는 문제
  NangPaGo-client/src/hooks/useRefrigerator.js
Labels: bug

#367 [NPG-260] 감사로그 클릭 후 다른 페이지로 이동 시 열어놨던 행이 닫히게 수정
  NangPaGo-admin/src/pages/Audit.jsx
Labels: chore

#368 [NO-ISSUE] 유저 레시피 작성 이미지 순서 맞도록 수정
  NangPaGo-client/src/pages/userRecipe/CreateUserRecipe.jsx
Labels: chore

#369 [NO-ISSUE] NangPago release/1.13.0 merge to main
  NangPaGo-admin/src/pages/Audit.jsx
  NangPaGo-admin/src/pages/Dashboard.jsx
  NangPaGo-admin/src/pages/Users.jsx
  NangPaGo-api/NangPaGo-admin/gradle.properties
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/audit/repository/AuditLogRepository.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/controller/DashboardController.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/dto/DashboardResponseDto.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/dto/HourlyUserActionCountDto.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/service/ChartService.java
  NangPaGo-api/NangPaGo-app/gradle.properties
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/firebase/service/FirebaseStorageService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user_recipe/service/UserRecipeService.java
  NangPaGo-api/NangPaGo-app/src/main/resources/application.yml
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/userRecipe/UserRecipe.java
  NangPaGo-client/src/components/layout/header/Header.jsx
  NangPaGo-client/src/components/userRecipe/ManualInput.jsx
  NangPaGo-client/src/hooks/useRefrigerator.js
  NangPaGo-client/src/pages/userRecipe/CreateUserRecipe.jsx
  NangPaGo-client/src/pages/userRecipe/ModifyUserRecipe.jsx
Labels: release

#370 [NO-ISSUE] 유저 레시피 수정하면서 조리과정 추가 시 이미지 업로드 안되던 버그 수정
  NangPaGo-client/src/pages/userRecipe/ModifyUserRecipe.jsx
Labels: chore

#371 [NPG-257] 개선 - 어드민 페이지에서 사용자 활동 분석 개선 (액션별 시간대 빈도수)
  NangPaGo-admin/src/components/util/dashboardUtils.jsx
  NangPaGo-admin/src/pages/Dashboard.jsx
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/audit/repository/AuditLogRepository.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/dto/HourlyUserActionCountDto.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/service/ChartService.java
Labels: enhancement

#372 [NO-ISSUE] NangPago release/1.14.0 merge to main
  NangPaGo-admin/src/components/util/dashboardUtils.jsx
  NangPaGo-admin/src/pages/Dashboard.jsx
  NangPaGo-api/NangPaGo-admin/gradle.properties
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/audit/repository/AuditLogRepository.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/dto/HourlyUserActionCountDto.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/service/ChartService.java
  NangPaGo-api/NangPaGo-app/gradle.properties
  NangPaGo-client/src/pages/userRecipe/ModifyUserRecipe.jsx
Labels: release

#373 [NPG-257] 버그: 사용자 활동 분석 차트 유저 레시피 카운트 안됨
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/service/ChartService.java
Labels: enhancement

#375 [NO-ISSUE] 글 작성 버튼 중복 클릭 방지
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/repository/CommunityRepository.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user_recipe/repository/UserRecipeRepository.java
  NangPaGo-client/src/components/button/SubmitButton.jsx
  NangPaGo-client/src/pages/community/CreateCommunity.jsx
  NangPaGo-client/src/pages/community/ModifyCommunity.jsx
  NangPaGo-client/src/pages/userRecipe/CreateUserRecipe.jsx
  NangPaGo-client/src/pages/userRecipe/ModifyUserRecipe.jsx
Labels: bug

#378 [NPG-267] README 수정
  README.md
  assets/cicd.png
  assets/server_architecture.png
  assets/thumbnail.png
Labels: documentation

#379 [NO-ISSUE] NangPago release/1.14.3 merge to main
  NangPaGo-api/NangPaGo-app/gradle.properties
  README.md
  assets/cicd.png
  assets/server_architecture.png
  assets/thumbnail.png
Labels: release
