Repository MARS-LIKELION/NangPaGo, pull requests merged in 2025-01, with the labels that each got.

#80 [NO-ISSUE] 개발 환경과 배포 환경 OAuth2 관련 URL 통일
  NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
  NangPaGo-fe/src/pages/login/Login.jsx
Labels: refactoring

#81 [NO-ISSUE] NangPago release/1.0.2 merge to main
  NangPaGo-be/gradle.properties
  NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
  NangPaGo-fe/src/pages/login/Login.jsx
Labels: release

#82 [Npg-77] logout 요청 URL `/api` 접두어 추가
  .github/workflows/cicd.yml
  NangPaGo-be/src/main/java/com/mars/NangPaGo/common/exception/GlobalExceptionHandler.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/auth/CustomLogoutFilter.java
  NangPaGo-fe/src/components/common/Header.jsx
Labels: bug, refactoring

#83 [NO-ISSUE] NangPago release/1.0.3 merge to main
  .github/workflows/cicd.yml
  NangPaGo-be/gradle.properties
  NangPaGo-be/src/main/java/com/mars/NangPaGo/common/exception/GlobalExceptionHandler.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/auth/CustomLogoutFilter.java
  NangPaGo-fe/src/components/common/Header.jsx
Labels: release

#84 [NPG-75] 클라이언트에서 댓글 작성시 중복 작성한 것처럼 보이는 버그 수정
  NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
  NangPaGo-fe/src/components/recipe/comment/RecipeComment.jsx
Labels: bug

#85 [NPG-75] 액세스 토큰이 만료시 새로고침하면 로그인 풀림 버그 수정
  NangPaGo-fe/src/components/common/Header.jsx
  NangPaGo-fe/src/slices/loginSlice.js
Labels: bug

#88 [NPG-75] 레시피 좋아요 사용자 인증 로직 변경
  NangPaGo-be/src/main/java/com/mars/NangPaGo/common/exception/NPGExceptionType.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/jwt/util/JwtFilter.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/controller/RecipeController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/repository/RecipeLikeRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/service/RecipeLikeService.java
  NangPaGo-fe/src/components/recipe/Recipe.jsx
Labels: refactoring

#89 [NPG-75] 네이버, 카카오 스코프 변경으로 인해 yml 수정
  NangPaGo-be/src/main/resources/application.yml
Labels: refactoring

#90 [NPG-75] 즐겨찾기 사용자 인증 방식 변경
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/controller/RecipeFavoriteController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/dto/RecipeFavoriteRequestDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/dto/RecipeFavoriteResponseDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/repository/RecipeFavoriteRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/service/RecipeFavoriteService.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/dto/RecipeLikeRequestDto.java
  NangPaGo-fe/src/components/recipe/Recipe.jsx
Labels: refactoring

#94 [NPG-83] push 직전 테스트 수행을 위한 pre-push 스크립트 작성
  .githooks/pre-push
Labels: enhancement

#91 [NPG-72] 한글 자동완성 개선 (초성 분리 가능)
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/controller/IngredientElasticController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/controller/IngredientEsController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/dto/IngredientEsResponseDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/entity/IngredientEs.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/repository/IngredientElasticRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/repository/IngredientEsRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/service/IngredientElasticSearchService.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/service/IngredientEsService.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/service/IngredientEsSynchronizer.java
  NangPaGo-be/src/main/resources/elastic/ingredient/post-mapping.json
  NangPaGo-be/src/main/resources/elastic/ingredient/post-setting.json
Labels: enhancement, refactoring

#93 [NPG-75] 댓글 응답 DTO 이메일 마스킹 처리 후 전송방식으로 변경
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/controller/RecipeCommentController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/dto/RecipeCommentRequestDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/dto/RecipeCommentResponseDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/service/RecipeCommentService.java
  NangPaGo-fe/src/components/recipe/comment/RecipeComment.jsx
Labels: refactoring

#92 [NPG-51] 검색버그수정 및 데이터베이스와 엘라스틱 동기화 기능 추가
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/controller/RecipeController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/dto/RecipeEsResponseDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/entity/RecipeEs.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/repository/RecipeESRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/service/RecipeEsService.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/service/RecipeEsSynchronizerService.java
Labels: bug, enhancement

#95 [NPG-87] 레시피 즐겨찾기 리스트 조회 API개발
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/controller/RecipeFavoriteController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/dto/RecipeFavoriteListResponseDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/repository/RecipeFavoriteRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/service/RecipeFavoriteService.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/controller/RecipeController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/service/RecipeEsService.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/service/RecipeEsSynchronizerService.java
  NangPaGo-fe/.gitignore
Labels: enhancement

#98 [NPG-90] csv에서 MySQL 및 ElasticSearch로 업로드하는 스크립트 작성
  NangPaGo-data/README.md
  NangPaGo-data/create_recipe_cleaned_csv.ipynb
  NangPaGo-data/elastic/ingredients_dictionary/create_bulk_type.py
  NangPaGo-data/elastic/ingredients_dictionary/init_csv2es_ingredients_dictionary.sh
  NangPaGo-data/mysql/ingredients_dictionary/init_csv2sql_ingredients_dictionary.py
  NangPaGo-data/mysql/ingredients_dictionary/query/create_ingredients_dictionary.sql
  NangPaGo-data/mysql/ingredients_dictionary/query/insert_ingredients_dictionary.sql
Labels: enhancement

#99 [NPG-63] Swagger 태그 추가
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/controller/RecipeCommentController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/controller/RecipeFavoriteController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/jwt/controller/TokenController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/refrigerator/controller/RefrigeratorController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/controller/AuthController.java
Labels: documentation

#100 [NPG-94] 키워드 없이 검색 시, 검색 실패 버그 수정
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/service/RecipeEsService.java
Labels: bug

#103 [NPG-95] 칼로리 단위표시
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/service/RecipeEsSynchronizerService.java
Labels: chore

#97 [NPG-81] 배포 환경에서 서버 로그를 파일로 남기도록 개선
  NangPaGo-be/src/main/resources/application.yml
Labels: refactoring

#104 [NPG-93] 레시피 리스트 UI 서버 연동 및 UI 개선
  NangPaGo-fe/src/components/recipe/Recipe.jsx
  NangPaGo-fe/src/components/recipe/RecipeCard.jsx
  NangPaGo-fe/src/components/recipe/RecipeListContent.jsx
Labels: enhancement

#107 [NPG-75] 로그인 상태유지 버그 수정
  NangPaGo-fe/src/api/axiosInstance.js
  NangPaGo-fe/src/components/recipe/RecipeListContent.jsx
  NangPaGo-fe/src/slices/loginSlice.js
Labels: bug

#108 [NO-ISSUE] React StrictMode 제거
  NangPaGo-fe/src/main.jsx
Labels: bug

#110 [NPG-89] Ingredient_id 칼럼 추가로 인한 리팩토링
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/dto/IngredientEsResponseDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/entity/Ingredient.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/entity/IngredientEs.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/service/IngredientEsService.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/service/IngredientEsSynchronizer.java
  NangPaGo-be/src/main/resources/elastic/ingredient/post-mapping.json
  NangPaGo-be/src/main/resources/elastic/ingredient/post-setting.json
  NangPaGo-data/README.md
  NangPaGo-data/elastic/ingredients_dictionary/create_bulk_type.py
  NangPaGo-data/elastic/ingredients_dictionary/init_index_ingredients_dictionary.sh
  NangPaGo-data/mysql/ingredients_dictionary/init_csv2sql_ingredients_dictionary.py
  NangPaGo-data/mysql/ingredients_dictionary/query/create_ingredients_dictionary.sql
  NangPaGo-data/mysql/ingredients_dictionary/query/insert_ingredients_dictionary.sql
Labels: refactoring

#111 [NPG-98] 사용자 인증 로직을 JWT 기반으로 개선
  NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/auth/aop/AuthenticatedUser.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/auth/aop/AuthenticationAspect.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/auth/component/AuthenticationHolder.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/auth/controller/AuthController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/auth/entrypoint/UnauthorizedEntryPoint.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/auth/enums/Provider.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/auth/factory/OAuth2UserInfoFactory.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/auth/factory/userinfo/GoogleUserInfo.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/auth/factory/userinfo/KakaoUserInfo.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/auth/factory/userinfo/NaverUserInfo.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/auth/factory/userinfo/OAuth2UserInfo.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/auth/filter/CustomLogoutFilter.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/auth/filter/JwtAuthenticationFilter.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/auth/handler/CustomSuccessHandler.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/auth/service/CustomLogoutService.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/auth/service/CustomOAuth2UserService.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/auth/vo/CustomOAuth2User.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/controller/RecipeCommentController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/service/RecipeCommentService.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/jwt/repository/RefreshTokenRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/jwt/service/TokenService.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/jwt/util/JwtFilter.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/jwt/util/JwtUtil.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/refrigerator/controller/RefrigeratorController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/refrigerator/service/RefrigeratorService.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/dto/UserRequestDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/entity/User.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/repository/UserRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/service/UserService.java
  NangPaGo-fe/src/api/axiosInstance.js
  NangPaGo-fe/src/components/recipe/RecipeListContent.jsx
  NangPaGo-fe/src/pages/recipe/RecipeList.jsx
  NangPaGo-fe/src/slices/loginSlice.js
Labels: bug, refactoring

#105 [NPG-80]레시피 즐겨찾기 기능 관련 수정
  NangPaGo-be/src/main/java/com/mars/NangPaGo/common/exception/NPGExceptionType.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/controller/RecipeFavoriteController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/dto/RecipeFavoriteListResponseDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/service/RecipeFavoriteService.java
Labels: bug

#112 [NPG-92] 회원정보수정 UI 구현
  NangPaGo-fe/src/components/mypage/UserInfoModify.jsx
  NangPaGo-fe/src/routes/Router.jsx
Labels: enhancement

#114 [NPG-72] ElasticSearch 검색 고도화
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/controller/IngredientEsController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/service/IngredientEsSynchronizer.java
  NangPaGo-be/src/main/resources/elastic/ingredient/post-setting.json
  NangPaGo-data/elastic/ingredients_dictionary/init_index_ingredients_dictionary.sh
Labels: bug, enhancement

#115 [NPG-53] 통합테스트 Support Utility 추가
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/entity/Ingredient.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/entity/Recipe.java
  NangPaGo-be/src/main/resources/application.yml
  NangPaGo-be/src/test/java/com/mars/NangPaGo/domain/recipe/repository/RecipeLikeRepositoryTest.java
  NangPaGo-be/src/test/java/com/mars/NangPaGo/domain/recipe/service/RecipeLikeServiceTest.java
  NangPaGo-be/src/test/java/com/mars/NangPaGo/domain/refrigerator/repository/RefrigeratorRepositoryTest.java
  NangPaGo-be/src/test/java/com/mars/NangPaGo/domain/refrigerator/service/RefrigeratorServiceTest.java
  NangPaGo-be/src/test/java/com/mars/NangPaGo/support/AbstractRepositoryTestSupport.java
  NangPaGo-be/src/test/java/com/mars/NangPaGo/support/IntegrationTestSupport.java
Labels: refactoring

#118 [NPG-76] Refrigerator.jsx 모듈화
  NangPaGo-fe/src/api/recipe.js
  NangPaGo-fe/src/components/recipe/RecipeCard.jsx
  NangPaGo-fe/src/components/recipe/RecipeListContent.jsx
  NangPaGo-fe/src/components/refrigerator/AddIngredientForm.jsx
  NangPaGo-fe/src/components/refrigerator/IngredientList.jsx
  NangPaGo-fe/src/components/search/EmptyState.jsx
  NangPaGo-fe/src/components/search/NoResult.jsx
  NangPaGo-fe/src/components/search/SearchResult.jsx
  NangPaGo-fe/src/components/util/stringUtil.jsx
  NangPaGo-fe/src/pages/recipe/RecipeList.jsx
  NangPaGo-fe/src/pages/refrigerator/Refrigerator.jsx
  NangPaGo-fe/src/pages/search/RefrigeratorSearch.jsx
Labels: refactoring

#119 refactor: 냉장고 식재료로 추천 레시피 구현
  NangPaGo-fe/src/api/recipe.js
  NangPaGo-fe/src/api/refrigerator.js
  NangPaGo-fe/src/pages/refrigerator/Refrigerator.jsx
  NangPaGo-fe/src/routes/Router.jsx
  NangPaGo-fe/src/slices/loginSlice.js
Labels: enhancement

#121 [NPG-76] 추천 레시피 UI 변경
  NangPaGo-fe/src/api/recipe.js
  NangPaGo-fe/src/pages/refrigerator/Refrigerator.jsx
  NangPaGo-fe/src/routes/Router.jsx
Labels: enhancement

#120 [NPG-107] Community 테이블 스키마 및 기본 기능 구현
  .gitignore
  NangPaGo-be/src/main/java/com/mars/NangPaGo/common/exception/NPGExceptionType.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/community/controller/CommunityCommentController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/community/dto/CommunityCommentRequestDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/community/dto/CommunityCommentResponseDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/community/entity/CommunityComment.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/community/repository/CommunityCommentRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/community/service/CommunityCommentService.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/entity/Community.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/entity/CommunityLike.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/repository/CommunityLikeRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/repository/CommunityRepository.java
  NangPaGo-data/mysql/ingredients_dictionary/query/create_ingredients_dictionary.sql
  NangPaGo-data/mysql/ingredients_dictionary/query/insert_ingredients_dictionary.sql
Labels: enhancement

#116 [NPG-74] 회원 정보 수정 기능 구현
  NangPaGo-be/src/main/java/com/mars/NangPaGo/common/exception/NPGExceptionType.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/controller/UserController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/dto/UserInfoRequestDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/dto/UserInfoResponseDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/entity/User.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/repository/UserRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/service/UserService.java
Labels: enhancement

#122 [NPG-76] 레시피 like 메서드 명 변경
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/controller/RecipeController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/service/RecipeLikeService.java
Labels: chore

#123 [NPG-101] 사용 안하는 Dto 컬럼 삭제
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/dto/UserInfoResponseDto.java
Labels: chore

#125 [NOISSUE] 탑버튼 구현
  NangPaGo-fe/src/components/common/CreateButton.jsx
  NangPaGo-fe/src/components/common/TopButton.jsx
  NangPaGo-fe/src/components/recipe/Recipe.jsx
  NangPaGo-fe/src/pages/recipe/RecipeList.jsx
  NangPaGo-fe/src/pages/refrigerator/Refrigerator.jsx
Labels: enhancement

#124 [NPG-109] 커뮤니티 게시물 좋아요 기능 API 구현
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/controller/CommunityLikeController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/dto/CommunityLikeResponseDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/entity/CommunityLike.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/repository/CommunityLikeRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/service/CommunityLikeService.java
Labels: enhancement

#126 [NPG-99] 이미지 업로드를 위한 firebase 연동
  NangPaGo-be/.gitignore
  NangPaGo-be/build.gradle
  NangPaGo-be/src/main/java/com/mars/NangPaGo/common/exception/NPGExceptionType.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/config/firebase/FirebaseConfig.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/firebase/controller/FirebaseStorageController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/firebase/service/FirebaseStorageService.java
  NangPaGo-be/src/main/resources/application.yml
  NangPaGo-be/src/test/java/com/mars/NangPaGo/support/AbstractRepositoryTestSupport.java
  NangPaGo-be/src/test/java/com/mars/NangPaGo/support/IntegrationTestSupport.java
Labels: enhancement

#127 [NPG-107] 커뮤니티 댓글 관련 주석 수정
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/community/controller/CommunityCommentController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/community/service/CommunityCommentService.java
Labels: chore

#130 [NPG-104] 레시피명으로 레시피 검색 기능 구현
  NangPaGo-be/src/main/java/com/mars/NangPaGo/common/exception/NPGExceptionType.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/builder/EsRecipeSearchQueryBuilder.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/controller/RecipeController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/service/RecipeEsService.java
  NangPaGo-fe/src/components/recipe/Recipe.jsx
  NangPaGo-fe/src/components/recipe/RecipeListContent.jsx
  NangPaGo-fe/src/components/search/SearchBar.jsx
  NangPaGo-fe/src/pages/recipe/RecipeList.jsx
  NangPaGo-fe/src/pages/search/RecipeSearch.jsx
  NangPaGo-fe/src/pages/search/Search.jsx
  NangPaGo-fe/src/routes/Router.jsx
Labels: enhancement, refactoring

#131 [NPG-110] CI/CD 파이프라인에 Firebase secret key 포함되도록 변경
  .github/workflows/cicd.yml
Labels: enhancement

#135 [NO-ISSUE] Service 레이어 테스트 유틸리티 구조 개선 (인증 관련)
  NangPaGo-be/src/test/java/com/mars/NangPaGo/domain/recipe/service/RecipeLikeServiceTest.java
  NangPaGo-be/src/test/java/com/mars/NangPaGo/provider/TestJwtProvider.java
  NangPaGo-be/src/test/java/com/mars/NangPaGo/support/IntegrationTestSupport.java
Labels: refactoring, test

#128 [NPG-92] 회원 정보 수정 페이지 UI 일부 수정, API 연결, 모달 창 추가
  NangPaGo-be/src/main/java/com/mars/NangPaGo/auth/factory/userinfo/NaverUserInfo.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/dto/UserRequestDto.java
  NangPaGo-fe/src/common/modal/UpdateUserInfoModal.jsx
  NangPaGo-fe/src/components/common/Header.jsx
  NangPaGo-fe/src/components/mypage/UserInfoModify.jsx
  NangPaGo-fe/src/routes/Router.jsx
Labels: enhancement

#137 [NO-ISSUE] ES warning 해결
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/builder/EsRecipeSearchQueryBuilder.java
Labels: bug

#129 [NPG-108] 게시물 CRUD 구현
  NangPaGo-be/src/main/java/com/mars/NangPaGo/config/security/SecurityConfig.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/community/controller/CommunityCommentController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/community/service/CommunityCommentService.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/controller/CommunityController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/dto/CommunityLikeResponseDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/dto/CommunityRequestDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/dto/CommunityResponseDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/entity/Community.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/repository/CommunityRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/service/CommunityService.java
Labels: enhancement

#138 [NPG-120] 전체 좋아요, 댓글 개수 기능 추가
  NangPaGo-be/src/main/java/com/mars/NangPaGo/config/security/SecurityConfig.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/controller/RecipeCommentController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/repository/RecipeCommentRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/service/RecipeCommentService.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/controller/RecipeController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/repository/RecipeLikeRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/service/RecipeLikeService.java
  NangPaGo-fe/src/api/commentService.js
  NangPaGo-fe/src/api/recipe.js
  NangPaGo-fe/src/components/mypage/UserInfoModify.jsx
  NangPaGo-fe/src/components/recipe/Recipe.jsx
  NangPaGo-fe/src/components/recipe/RecipeCard.jsx
  NangPaGo-fe/src/components/recipe/comment/RecipeComment.jsx
Labels: enhancement

#139 [NPG-119] UI 헤더 - `nickname`으로 보여주도록 변경, 검증 로직 개선
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/controller/UserController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/dto/UserResponseDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/service/UserService.java
  NangPaGo-fe/src/components/common/Header.jsx
  NangPaGo-fe/src/components/mypage/UserInfoModify.jsx
  NangPaGo-fe/src/slices/loginSlice.js
Labels: refactoring

#143 [NO-ISSUE] ES recipes 인덱스 bulk-update 지우고 다시쓰기
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/service/RecipeEsSynchronizerService.java
Labels: refactoring

#142 [NPG-108] 게시물 좋아요 개수 조회 API 추가
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/controller/CommunityLikeController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/repository/CommunityLikeRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/service/CommunityLikeService.java
Labels: enhancement

#144 [NO_ISSUE] 무한 재요청 수정
  NangPaGo-fe/src/api/recipe.js
  NangPaGo-fe/src/components/recipe/RecipeListContent.jsx
  NangPaGo-fe/src/pages/recipe/RecipeList.jsx
Labels: bug

#141 [NPG-115] 커뮤니티 기능 추가 구현
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/controller/CommunityController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/dto/CommunityRequestDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/entity/Community.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/service/CommunityService.java
Labels: enhancement

#146 [NO-ISSU] 게시글 단일 조회 권한 로직 개선
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/service/CommunityService.java
Labels: bug

#145 [NPG-118] 커뮤니티 전체 목록 조회 구현
  NangPaGo-be/src/main/java/com/mars/NangPaGo/NangPaGoApplication.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/controller/CommunityController.java
  NangPaGo-fe/src/api/community.js
  NangPaGo-fe/src/components/common/Header.jsx
  NangPaGo-fe/src/pages/community/CommunityList.jsx
  NangPaGo-fe/src/pages/recipe/RecipeList.jsx
  NangPaGo-fe/src/routes/Router.jsx
Labels: enhancement

#147 [NPG-124] 레시피 검색 화면 자동완성 highlight 적용
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/dto/RecipeEsResponseDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/service/RecipeEsService.java
  NangPaGo-fe/src/pages/search/RecipeSearch.jsx
Labels: enhancement

#148 [NPG-116] 검색 UI Debounce 적용
  NangPaGo-fe/src/hooks/useDebounce.js
  NangPaGo-fe/src/pages/search/RecipeSearch.jsx
  NangPaGo-fe/src/pages/search/RefrigeratorSearch.jsx
Labels: enhancement

#149 [NPG-144] 검색어 입력 영역 클릭시 초기화되는 버그 해결
  NangPaGo-fe/src/components/search/SearchBar.jsx
  NangPaGo-fe/src/pages/recipe/RecipeList.jsx
  NangPaGo-fe/src/pages/search/RecipeSearch.jsx
  NangPaGo-fe/src/pages/search/RefrigeratorSearch.jsx
Labels: bug

#151 [NPG-125] 커뮤니티 게시물 단일조회 FE 구현
  NangPaGo-fe/src/api/community.js
  NangPaGo-fe/src/api/communityComment.js
  NangPaGo-fe/src/components/community/Community.jsx
  NangPaGo-fe/src/components/community/comment/CommunityComment.jsx
  NangPaGo-fe/src/pages/community/CommunityDetail.jsx
  NangPaGo-fe/src/routes/Router.jsx
Labels: enhancement

#154 [NO-ISSUE] 게시글 수정 구현 및 공통 컴포넌트 모듈화
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/dto/CommunityRequestDto.java
  NangPaGo-fe/src/api/community.js
  NangPaGo-fe/src/components/common/ErrorMessage.jsx
  NangPaGo-fe/src/components/common/SubmitButton.jsx
  NangPaGo-fe/src/components/community/Community.jsx
  NangPaGo-fe/src/components/community/FileUpload.jsx
  NangPaGo-fe/src/components/community/TextArea.jsx
  NangPaGo-fe/src/components/community/TextInput.jsx
  NangPaGo-fe/src/pages/community/CommunityDetail.jsx
  NangPaGo-fe/src/pages/community/CreateCommunity.jsx
  NangPaGo-fe/src/pages/community/ModifyCommunity.jsx
  NangPaGo-fe/src/routes/Router.jsx
Labels: enhancement

#150 [NPG-115] 커뮤니티 기본 사진 등록
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/dto/CommunityResponseDto.java
Labels: enhancement

#152 [NPG-103] 마이페이지 메뉴별 조회 기능 추가
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/repository/RecipeCommentRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/repository/RecipeLikeRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/controller/UserController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/dto/MyPageDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/service/UserService.java
  NangPaGo-fe/package-lock.json
  NangPaGo-fe/package.json
  NangPaGo-fe/src/api/myPage.js
  NangPaGo-fe/src/components/common/Header.jsx
  NangPaGo-fe/src/components/profile/ItemList.jsx
  NangPaGo-fe/src/components/profile/ProfileHeader.jsx
  NangPaGo-fe/src/components/profile/ProfileTabs.jsx
  NangPaGo-fe/src/pages/mypage/Modify.jsx
  NangPaGo-fe/src/pages/mypage/Profile.jsx
  NangPaGo-fe/src/routes/Router.jsx
Labels: enhancement

#155 [NO-ISSUE] 커뮤니티 - 게시글 소유자 확인 로직 버그 수정
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/controller/CommunityController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/entity/Community.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/service/CommunityService.java
Labels: bug

#156 [NPG-128] 커뮤니티 전체 조회 - 좋아요 & 댓글 집계 API 구현
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/community/repository/CommunityCommentRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/dto/CommunityResponseDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/repository/CommunityLikeRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/service/CommunityService.java
  NangPaGo-fe/src/pages/community/CommunityList.jsx
Labels: enhancement

#158 [NPG-127] 레시피 리스트 응답에 좋아요, 댓글 집계 추가
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/dto/RecipeEsResponseDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/service/RecipeEsService.java
  NangPaGo-fe/src/api/commentService.js
  NangPaGo-fe/src/components/recipe/RecipeCard.jsx
Labels: refactoring

#159 [NO-ISSUE] 마이페이지 탭 조회 버그 수정
  NangPaGo-be/src/main/java/com/mars/NangPaGo/common/exception/NPGExceptionType.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/controller/RecipeController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/controller/UserController.java
  NangPaGo-fe/src/pages/mypage/Profile.jsx
Labels: bug, refactoring

#160 [NO-ISSUE] 게시물 CRUD 구현
  NangPaGo-be/src/main/java/com/mars/NangPaGo/NangPaGoApplication.java
  NangPaGo-fe/src/components/common/CreateButton.jsx
  NangPaGo-fe/src/components/community/Community.jsx
  NangPaGo-fe/src/components/community/TextArea.jsx
  NangPaGo-fe/src/pages/community/CommunityDetail.jsx
  NangPaGo-fe/src/pages/community/CommunityList.jsx
  NangPaGo-fe/src/pages/community/CreateCommunity.jsx
  NangPaGo-fe/src/pages/community/ModifyCommunity.jsx
Labels: enhancement

#161 [NO-ISSUE] 무한스크롤 렌더링 시 같은 ID 부여 필터 적용
  NangPaGo-fe/src/pages/community/CreateCommunity.jsx
  NangPaGo-fe/src/pages/mypage/Profile.jsx
Labels: bug

#167 [NO-ISSUE] 마이페이지 레이아웃 문제 해결
  NangPaGo-fe/src/pages/mypage/Modify.jsx
Labels: bug

#168 [NO-ISSUE] 메인페이지 즐겨찾기 탭 텍스트 변경
  NangPaGo-fe/src/components/common/Header.jsx
  NangPaGo-fe/src/components/recipe/RecipeListContent.jsx
  NangPaGo-fe/src/pages/recipe/RecipeList.jsx
Labels: chore

#169 [NO-ISSUE] NangPago release/1.3.1 merge to main
  NangPaGo-be/gradle.properties
  NangPaGo-fe/src/components/common/Footer.jsx
  NangPaGo-fe/src/components/common/Header.jsx
  NangPaGo-fe/src/components/recipe/RecipeListContent.jsx
  NangPaGo-fe/src/pages/mypage/Modify.jsx
  NangPaGo-fe/src/pages/recipe/RecipeList.jsx
Labels: release

#173 [NPG-138] 커뮤니티 비공개 체크박스에 설명 제거
  NangPaGo-fe/src/pages/community/CreateCommunity.jsx
Labels: chore

#174 [NPG-137] BugFix - UI에서 불필요한 소스 field 제거
  NangPaGo-fe/src/components/recipe/Recipe.jsx
Labels: bug

#175 [NPG-139] 좋아요 상태 버그 수정
  NangPaGo-fe/src/api/community.js
  NangPaGo-fe/src/components/community/Community.jsx
Labels: bug

#176 [NPG-146] 로그인 전/후 즐겨찾기 탭 수정
  NangPaGo-fe/src/components/recipe/RecipeListContent.jsx
  NangPaGo-fe/src/components/recipe/RecipeListTab.jsx
  NangPaGo-fe/src/pages/recipe/RecipeList.jsx
Labels: chore

#177 [NPG-133] BugFix - UI에서 사진을 변경하지 않았을 때 기존 이미지가 유지되도록 수정
  NangPaGo-fe/src/pages/community/CreateCommunity.jsx
  NangPaGo-fe/src/pages/community/ModifyCommunity.jsx
Labels: bug

#180 [NPG-143] UI 헤더 현재 위치 표시(활성화) 및 제목 표시
  NangPaGo-fe/src/components/common/Header.jsx
Labels: chore

#181 [NPG-134] 메인과 상세 뷰의 이미지 레이아웃 통일
  NangPaGo-fe/src/components/common/Image.jsx
  NangPaGo-fe/src/components/community/Community.jsx
  NangPaGo-fe/src/components/community/CommunityCard.jsx
  NangPaGo-fe/src/components/community/FileUpload.jsx
  NangPaGo-fe/src/components/recipe/CookingSteps.jsx
  NangPaGo-fe/src/components/recipe/Recipe.jsx
  NangPaGo-fe/src/components/recipe/RecipeCard.jsx
  NangPaGo-fe/src/pages/community/CommunityList.jsx
Labels: chore

#183 [NPG-149] 커뮤니티 게시물: 이미지 취소 버튼 추가
  NangPaGo-fe/src/components/community/FileUpload.jsx
  NangPaGo-fe/src/pages/community/CreateCommunity.jsx
  NangPaGo-fe/src/pages/community/ModifyCommunity.jsx
Labels: bug, enhancement

#166 [NPG-122] 회원 탈퇴 기능 추가
  NangPaGo-be/src/main/java/com/mars/NangPaGo/auth/handler/OAuth2SuccessHandler.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/auth/service/OAuth2UserService.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/auth/vo/OAuth2RequestResolver.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/auth/vo/OAuth2UserImpl.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/common/exception/NPGExceptionType.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/config/security/OAuth2Config.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/config/security/SecurityConfig.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/auth/entity/OAuthProviderToken.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/auth/factory/OAuth2TokenFactory.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/auth/factory/oauth2tokeninfo/GoogleTokenInfo.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/auth/factory/oauth2tokeninfo/KakaoTokenInfo.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/auth/factory/oauth2tokeninfo/NaverTokenInfo.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/auth/factory/oauth2tokeninfo/OAuth2TokenInfo.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/auth/repository/OAuthProviderTokenRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/auth/service/OAuth2ProviderTokenService.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/controller/UserController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/dto/UserRequestDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/entity/User.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/enums/UserStatus.java
  NangPaGo-be/src/main/resources/application.yml
Labels: enhancement

#185 [NPG-152] UI 헤더 - 현재 위치 구분, 아이콘 색상 변경, 드롭다운 위치 조정
  NangPaGo-fe/src/components/common/Header.jsx
Labels: bug

#188 [NPG-141] 커뮤니티 게시물 - 이미지 업로드 용량 10MB 제한 추가
  NangPaGo-fe/src/common/modal/FileSizeErrorModal.jsx
  NangPaGo-fe/src/pages/community/CreateCommunity.jsx
  NangPaGo-fe/src/pages/community/ModifyCommunity.jsx
Labels: enhancement

#187 [NPG-136] 중복 회원가입 방지 로직
  NangPaGo-be/src/main/java/com/mars/NangPaGo/auth/handler/OAuth2SuccessHandler.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/auth/service/OAuth2UserService.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/auth/service/OAuth2ProviderTokenService.java
  NangPaGo-fe/src/pages/error/OAuthError.jsx
  NangPaGo-fe/src/routes/Router.jsx
Labels: refactoring

#189 [ NPG-150] Jenkins 빌드 스크립트 작성
  Jenkinsfile
  NangPaGo-be/Dockerfile-be
  NangPaGo-be/build.gradle
  NangPaGo-fe/Dockerfile-fe
  docker-compose.yml
  docker/docker-compose.blue.yml
  docker/docker-compose.green.yml
  scripts/deploy.sh
Labels: enhancement

#186 [NPG-140] 커뮤니티 게시글 예외 발생 메시지 전달 구조 개선
  NangPaGo-be/src/main/java/com/mars/NangPaGo/common/exception/GlobalExceptionHandler.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/controller/CommunityController.java
  NangPaGo-fe/src/api/community.js
  NangPaGo-fe/src/pages/community/CreateCommunity.jsx
  NangPaGo-fe/src/pages/community/ModifyCommunity.jsx
Labels: refactoring

#190 [NPG-142] 레시피 좋아요 갯수 sync 안맞는 문제
  NangPaGo-fe/src/pages/refrigerator/Refrigerator.jsx
Labels: bug

#194 [NPG-150] Actions 스크립트에서 `deploy` Job 제거
  .github/workflows/ci.yml
  .github/workflows/cicd.yml
Labels: chore

#193 [NPG-154] 식재료가 없을경우 '레시피 찾기'버튼 비활성화
  NangPaGo-fe/src/pages/refrigerator/Refrigerator.jsx
Labels: chore

#196 [ NPG-156] 냉장고 식재료 체크박스 추가
  NangPaGo-fe/package-lock.json
  NangPaGo-fe/package.json
  NangPaGo-fe/src/components/refrigerator/IngredientList.jsx
  NangPaGo-fe/src/pages/refrigerator/Refrigerator.jsx
  NangPaGo-fe/tailwind.config.js
Labels: chore

#197 [NPG-150] 배포 이미지에 version 태그 추가
  Jenkinsfile
  docker/docker-compose.blue.yml
  docker/docker-compose.green.yml
  scripts/deploy.sh
Labels: chore

#199 [NPG-150] Jenkins 빌드 및 배포 웹훅 설정
  Jenkinsfile
Labels: enhancement

#200 [NPG-147] 메인페이지 UI/UX 개선 및 반응형 구현
  NangPaGo-be/src/main/java/com/mars/NangPaGo/auth/filter/JwtAuthenticationFilter.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/controller/RecipeController.java
  NangPaGo-fe/src/api/recipe.js
  NangPaGo-fe/src/components/common/Footer.jsx
  NangPaGo-fe/src/components/common/Header.jsx
  NangPaGo-fe/src/components/common/TopButton.jsx
  NangPaGo-fe/src/components/community/Community.jsx
  NangPaGo-fe/src/components/layout/header/Header.jsx
  NangPaGo-fe/src/components/layout/header/NavItem.jsx
  NangPaGo-fe/src/components/layout/header/ProfileDropdown.jsx
  NangPaGo-fe/src/components/recipe/Recipe.jsx
  NangPaGo-fe/src/components/recipe/RecipeCard.jsx
  NangPaGo-fe/src/components/recipe/RecipeListContent.jsx
  NangPaGo-fe/src/components/recipe/RecipeListTab.jsx
  NangPaGo-fe/src/components/search/SearchBar.jsx
  NangPaGo-fe/src/globals.css
  NangPaGo-fe/src/pages/community/CommunityList.jsx
  NangPaGo-fe/src/pages/community/CreateCommunity.jsx
  NangPaGo-fe/src/pages/community/ModifyCommunity.jsx
  NangPaGo-fe/src/pages/mypage/Modify.jsx
  NangPaGo-fe/src/pages/mypage/Profile.jsx
  NangPaGo-fe/src/pages/recipe/RecipeList.jsx
  NangPaGo-fe/src/pages/refrigerator/Refrigerator.jsx
  NangPaGo-fe/src/pages/search/RecipeSearch.jsx
  NangPaGo-fe/tailwind.config.js
Labels: refactoring

#201 [NPG-147] 로그인 페이지 UI/UX 개선
  NangPaGo-fe/src/components/login/SocialLoginButton.jsx
  NangPaGo-fe/src/components/recipe/RecipeListContent.jsx
  NangPaGo-fe/src/globals.css
  NangPaGo-fe/src/pages/login/Login.jsx
Labels: refactoring

#184 [NPG-145] 탭 전환시 이전 데이터 초기화 버그 수정
  NangPaGo-be/src/main/java/com/mars/NangPaGo/config/security/SecurityConfig.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/controller/UserController.java
  NangPaGo-fe/src/api/commentService.js
  NangPaGo-fe/src/api/communityComment.js
  NangPaGo-fe/src/api/myPage.js
  NangPaGo-fe/src/components/profile/ItemList.jsx
  NangPaGo-fe/src/hooks/useMyPageInfo.js
  NangPaGo-fe/src/hooks/useTabData.js
  NangPaGo-fe/src/pages/mypage/Profile.jsx
Labels: bug

#202 [NPG-157] 게시글 작성 중 사용자 액션 차단
  NangPaGo-fe/src/components/common/Header.jsx
  NangPaGo-fe/src/components/community/Community.jsx
  NangPaGo-fe/src/pages/community/CommunityList.jsx
  NangPaGo-fe/src/pages/community/CreateCommunity.jsx
  NangPaGo-fe/src/pages/community/ModifyCommunity.jsx
Labels: enhancement

#205 [NO-ISSUE] NangPago release/1.4.1 merge to main
  NangPaGo-be/gradle.properties
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/community/controller/CommunityCommentController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/controller/RecipeCommentController.java
  NangPaGo-fe/src/api/communityComment.js
Labels: release

#207 [NPG-157] 리팩토링 - Hedaer.jsx (게시글 작성 중 사용자 액션 차단)
  NangPaGo-fe/src/components/common/Header.jsx
  NangPaGo-fe/src/components/layout/header/Header.jsx
  NangPaGo-fe/src/components/layout/header/NavItem.jsx
  NangPaGo-fe/src/components/layout/header/ProfileDropdown.jsx
  NangPaGo-fe/src/pages/community/CreateCommunity.jsx
  NangPaGo-fe/src/pages/community/ModifyCommunity.jsx
Labels: refactoring

#198 [NPG-151] 커뮤니티 뒤로가기 경로에 따른 리다이렉션 조건 추가
  NangPaGo-fe/src/pages/community/CommunityDetail.jsx
  NangPaGo-fe/src/pages/community/CreateCommunity.jsx
  NangPaGo-fe/src/pages/community/ModifyCommunity.jsx
Labels: enhancement

#206 [NPG-148] Access token & Refresh token에 id 클레임 추가
  NangPaGo-be/src/main/java/com/mars/NangPaGo/auth/handler/OAuth2SuccessHandler.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/common/util/JwtUtil.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/auth/service/TokenService.java
  NangPaGo-be/src/test/java/com/mars/NangPaGo/provider/TestJwtProvider.java
Labels: refactoring

#209 [NO-ISSUE] `logo.png` 관련 경고 로그 표출 해결
  NangPaGo-fe/src/components/layout/header/Header.jsx
Labels: bug

#208 [NPG-159] 레시피 상세조회 좋아요 및 즐겨찾기 비로그인시 모달 표시
  NangPaGo-fe/src/common/modal/LoginModal.jsx
  NangPaGo-fe/src/components/recipe/Recipe.jsx
Labels: chore

#72 [NPG-74] 레시피 즐겨찾기 관련 서비스 테스트 코드 추가
  NangPaGo-be/src/test/java/com/mars/NangPaGo/domain/favorite/recipe/service/RecipeFavoriteServiceTest.java
Labels: test

#87 [NPG-74] 레시피 댓글 관련 테스트 코드 추가
  NangPaGo-be/src/test/java/com/mars/NangPaGo/domain/comment/recipe/service/RecipeCommentServiceTest.java
Labels: test

#211 [NPG-147] 마이페이지 UI/UX 개선 및 탑버튼 영역 수정
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/dto/RecipeCommentResponseDto.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/repository/RecipeCommentRepository.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/service/RecipeCommentService.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/service/UserService.java
  NangPaGo-fe/src/common/modal/UpdateUserInfoModal.jsx
  NangPaGo-fe/src/components/common/CreateButton.jsx
  NangPaGo-fe/src/components/common/Footer.jsx
  NangPaGo-fe/src/components/common/SubmitButton.jsx
  NangPaGo-fe/src/components/layout/header/ProfileDropdown.jsx
  NangPaGo-fe/src/components/profile/ItemList.jsx
  NangPaGo-fe/src/components/profile/ProfileHeader.jsx
  NangPaGo-fe/src/components/profile/ProfileTabs.jsx
  NangPaGo-fe/src/pages/mypage/Modify.jsx
  NangPaGo-fe/src/pages/mypage/Profile.jsx
  NangPaGo-fe/src/pages/recipe/RecipeList.jsx
  NangPaGo-fe/tailwind.config.js
Labels: refactoring

#213 [NO-ISSUE] 중복 이메일 회원가입 방지 로직 에러
  NangPaGo-be/src/main/java/com/mars/NangPaGo/auth/handler/OAuth2SuccessHandler.java
Labels: bug

#212 [NPG-153] Footer 클릭 시 모달로 현재 배포 버전 표시
  NangPaGo-be/src/main/java/com/mars/NangPaGo/config/security/SecurityConfig.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/build/BuildVersionController.java
  NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/build/BuildVersionProperties.java
  NangPaGo-fe/src/api/footer.js
  NangPaGo-fe/src/common/modal/BuildVersionModal.jsx
  NangPaGo-fe/src/components/common/Footer.jsx
Labels: enhancement

#216 [NPG-160] 리액트 라우팅에서 비로그인 사용자 접근 제한
  NangPaGo/NangPaGo-app/frontend/src/components/layout/header/Header.jsx
  NangPaGo/NangPaGo-app/frontend/src/pages/error/UnauthenticatedAccess.jsx
  NangPaGo/NangPaGo-app/frontend/src/routes/AuthenticatedRoute.jsx
  NangPaGo/NangPaGo-app/frontend/src/routes/Router.jsx
  NangPaGo/NangPaGo-app/frontend/src/slices/loginSlice.js
Labels: enhancement

#215 [NPG-147] 레시피 검색 UI 수정
  NangPaGo/NangPaGo-app/frontend/src/api/recipe.js
  NangPaGo/NangPaGo-app/frontend/src/components/recipe/Recipe.jsx
  NangPaGo/NangPaGo-app/frontend/src/components/recipe/RecipeListContent.jsx
  NangPaGo/NangPaGo-app/frontend/src/components/search/EmptyState.jsx
  NangPaGo/NangPaGo-app/frontend/src/components/search/NoResult.jsx
  NangPaGo/NangPaGo-app/frontend/src/components/search/SearchInput.jsx
  NangPaGo/NangPaGo-app/frontend/src/components/search/SearchResult.jsx
  NangPaGo/NangPaGo-app/frontend/src/components/util/stringUtil.jsx
  NangPaGo/NangPaGo-app/frontend/src/hooks/useRecipeSearch.js
  NangPaGo/NangPaGo-app/frontend/src/pages/search/RecipeSearch.jsx
Labels: refactoring

#219 [NPG-147] 커뮤니티 리스트 UI 수정
  NangPaGo/NangPaGo-app/frontend/src/components/common/CreateButton.jsx
  NangPaGo/NangPaGo-app/frontend/src/components/community/Community.jsx
  NangPaGo/NangPaGo-app/frontend/src/components/community/CommunityCard.jsx
  NangPaGo/NangPaGo-app/frontend/src/components/community/FileUpload.jsx
  NangPaGo/NangPaGo-app/frontend/src/components/community/TextArea.jsx
  NangPaGo/NangPaGo-app/frontend/src/components/community/TextInput.jsx
  NangPaGo/NangPaGo-app/frontend/src/pages/community/CommunityList.jsx
  NangPaGo/NangPaGo-app/frontend/src/pages/community/CreateCommunity.jsx
  NangPaGo/NangPaGo-app/frontend/src/pages/community/ModifyCommunity.jsx
Labels: refactoring

#210 [NPG-161] CommunityService Test코드 작성
  NangPaGo/NangPaGo-app/src/main/java/com/mars/app/domain/community/service/CommunityLikeService.java
  NangPaGo/NangPaGo-app/src/test/java/com/mars/app/domain/community/service/CommunityLikeServiceTest.java
  NangPaGo/NangPaGo-app/src/test/java/com/mars/app/domain/community/service/CommunityServiceTest.java
Labels: test

#217 [NPG-147] 냉장고 UI 수정
  NangPaGo/NangPaGo-app/frontend/index.html
  NangPaGo/NangPaGo-app/frontend/src/api/refrigerator.js
  NangPaGo/NangPaGo-app/frontend/src/components/recipe/RecipeCard.jsx
  NangPaGo/NangPaGo-app/frontend/src/components/refrigerator/AddIngredientForm.jsx
  NangPaGo/NangPaGo-app/frontend/src/components/refrigerator/IngredientList.jsx
  NangPaGo/NangPaGo-app/frontend/src/components/search/SearchInput.jsx
  NangPaGo/NangPaGo-app/frontend/src/hooks/useRefrigerator.js
  NangPaGo/NangPaGo-app/frontend/src/pages/refrigerator/Refrigerator.jsx
  NangPaGo/NangPaGo-app/frontend/src/pages/search/RefrigeratorSearch.jsx
  NangPaGo/NangPaGo-app/src/test/java/com/mars/app/domain/community/service/CommunityServiceTest.java
Labels: refactoring

#223 [NPG-162] 즐겨찾기 페이지 처리 및 좋아요/댓글수 표시
  NangPaGo/NangPaGo-app/frontend/src/api/recipe.js
  NangPaGo/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/controller/RecipeFavoriteController.java
  NangPaGo/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/dto/RecipeFavoriteListResponseDto.java
  NangPaGo/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/service/RecipeFavoriteService.java
  NangPaGo/NangPaGo-app/src/main/java/com/mars/app/domain/user/service/UserService.java
  NangPaGo/NangPaGo-app/src/test/java/com/mars/app/domain/favorite/recipe/service/RecipeFavoriteServiceTest.java
Labels: bug

#228 [NO-ISSUE] 냉파고 App CI/CD script 변경
  NangPaGo-api/NangPaGo-app/Dockerfile
  NangPaGo-api/NangPaGo-app/Dockerfile-app-be
  NangPaGo-api/NangPaGo-app/docker/docker-compose.blue.yml
  NangPaGo-api/NangPaGo-app/docker/docker-compose.green.yml
  NangPaGo-client/Dockerfile-app-fe
  deploy/nangpago-app/deploy.sh
  docker/nangpago-app/docker-compose.blue.yml
  docker/nangpago-app/docker-compose.green.yml
  jenkins/nangpago-app/Jenkinsfile
Labels: refactoring

#227 [NPG-166] 리액트에서 404 에러 처리 (NotFound 페이지 이동)
  NangPaGo-client/src/pages/error/NotFound.jsx
  NangPaGo-client/src/routes/Router.jsx
Labels: enhancement

#226 [NPG-135]좋아요 수, 댓글 수에 따라 검색결과 내림차순 정렬하여 반환
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/builder/EsRecipeSearchQueryBuilder.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/service/RecipeEsService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/service/RecipeEsSynchronizerService.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/recipe/RecipeEs.java
Labels: chore

#230 [NO-ISSUE] 불필요한 White list 제거
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/config/SecurityConfig.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/config/security/SecurityConfig.java
Labels: chore

#233 [NO-ISSUE] 테스트 코드 영역 - `ddl-auto` 설정값 변경
  NangPaGo-api/NangPaGo-app/src/main/resources/application.yml
Labels: chore

#232 [NPG-167] 관리자 패스워드 암호화 추가
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/auth/service/UserDetailServiceImpl.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/config/SecurityConfig.java
Labels: enhancement

#234 [NPG-170] 공통 에러 페이지 컴포넌트 개발
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/auth/handler/OAuth2SuccessHandler.java
  NangPaGo-client/src/pages/error/Error.jsx
  NangPaGo-client/src/pages/error/OAuthError.jsx
  NangPaGo-client/src/routes/Router.jsx
Labels: enhancement

#235 [NPG-169] 레시피 좋아요 카운트 수 실시간 반응 구현
  NangPaGo-api/NangPaGo-app/build.gradle
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/config/rabbitmq/RabbitMQConfig.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/config/security/SecurityConfig.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/controller/RecipeController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/messaging/LikeNotificationConsumer.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/messaging/LikeNotificationPublisher.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/messaging/SseEmitterService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/service/RecipeLikeService.java
  NangPaGo-api/NangPaGo-app/src/main/resources/application.yml
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/exception/NPGExceptionType.java
  NangPaGo-client/src/api/recipe.js
  NangPaGo-client/src/hooks/useRecipeData.js
  NangPaGo-client/src/slices/loginSlice.js
Labels: enhancement

#239 [NPG-182] 불필요한 alert 제거
  NangPaGo-admin/src/pages/Login.jsx
Labels: chore

#240 [NPG-181] 댓글 작성 keypress 제거, 댓글 UI 개선
  NangPaGo-client/src/common/modal/FileSizeErrorModal.jsx
  NangPaGo-client/src/components/community/Community.jsx
  NangPaGo-client/src/components/community/comment/CommunityComment.jsx
  NangPaGo-client/src/components/recipe/comment/CommentForm.jsx
  NangPaGo-client/src/components/recipe/comment/CommentList.jsx
  NangPaGo-client/src/components/recipe/comment/RecipeComment.jsx
  NangPaGo-client/src/pages/community/CommunityDetail.jsx
  NangPaGo-client/src/pages/search/RefrigeratorSearch.jsx
Labels: bug, chore

#241 [NO-ISSUE] App, Admin 프로젝트별 버전 별도 관리
  NangPaGo-api/NangPaGo-admin/build.gradle
  NangPaGo-api/NangPaGo-admin/gradle.properties
  NangPaGo-api/NangPaGo-app/build.gradle
  NangPaGo-api/NangPaGo-app/gradle.properties
  NangPaGo-api/build.gradle
  NangPaGo-api/gradle.properties
Labels: chore

#254 [NO-ISSUE] 레시피 좋아요 기능 비동기 처리
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/config/rabbitmq/RabbitMQConfig.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/controller/RecipeController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/dto/RecipeLikeMessageDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/dto/RecipeLikeResponseDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/messaging/LikeNotificationConsumer.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/messaging/LikeNotificationPublisher.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/messaging/SseEmitterService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/repository/RecipeLikeRepository.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/service/RecipeLikeMessageService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/service/RecipeLikeService.java
  NangPaGo-api/NangPaGo-app/src/main/resources/application.yml
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/recipe/messaging/LikeNotificationConsumerTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/recipe/service/RecipeLikeMessageServiceTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/recipe/service/RecipeLikeServiceTest.java
  NangPaGo-client/src/hooks/useRecipeData.js
Labels: enhancement

#247 [NPG-178] Admin 사용자 관리 페이지 화면 기획
  NangPaGo-admin/src/pages/Users.jsx
Labels: enhancement

#250 [NPG-193] 댓글 작성 이후 1페이지로 전환
  NangPaGo-client/src/components/comment/Comment.jsx
Labels: chore

#255 [NPG-195] 식재료 추가가 안되는 버그 수정
  NangPaGo-client/src/components/util/stringUtil.jsx
Labels: bug

#252 [NPG-194] 재료 검색창 뒤로가기 버튼 색 수정
  NangPaGo-client/src/pages/search/RecipeSearch.jsx
  NangPaGo-client/src/pages/search/RefrigeratorSearch.jsx
Labels: chore

#248 [NPG-183] 관리자 대시보드 - 총 사용자, 총 게시글 집계 기능 구현
  NangPaGo-admin/src/api/total.js
  NangPaGo-admin/src/main.jsx
  NangPaGo-admin/src/pages/Home.jsx
  NangPaGo-admin/src/pages/Login.jsx
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/chart/controller/ChartController.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/chart/service/ChartService.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/community/repository/CommunityRepository.java
Labels: enhancement

#249 [NPG-196] 마이페이지 댓글에서 Recipe ID 매핑 오류와 관련 Dto 수정
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/community/dto/CommunityCommentResponseDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/recipe/dto/RecipeCommentResponseDto.java
  NangPaGo-client/src/components/profile/ItemList.jsx
Labels: bug

#251 [NPG-197] 마이페이지 댓글 내용에서 개행 문자 처리 추가
  NangPaGo-client/src/components/profile/ItemList.jsx
Labels: enhancement

#259 [NO-ISSUE] 관리자 페이지 - Login URI 수정
  NangPaGo-admin/src/pages/Login.jsx
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/config/SecurityConfig.java
Labels: bug

#260 [NO-ISSUE] 관리자 페이지 - Logout URI 수정
  NangPaGo-admin/src/components/DashboardLayout.jsx
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/config/SecurityConfig.java
Labels: bug

#261 [NPG-184] 토큰 재발급 실패시 로그아웃 처리
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/auth/filter/JwtAuthenticationFilter.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/auth/handler/AdminSuccessHandler.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/auth/service/AdminLogoutSuccessHandler.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/config/SecurityConfig.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/auth/service/TokenService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/auth/filter/JwtAuthenticationFilter.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/auth/handler/OAuth2SuccessHandler.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/auth/service/OAuth2LogoutService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/config/security/SecurityConfig.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/auth/controller/AuthController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/auth/service/TokenService.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/provider/TestJwtProvider.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/support/IntegrationTestSupport.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/util/web/CookieUtil.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/util/web/JwtUtil.java
  NangPaGo-client/src/api/axiosInstance.js
  NangPaGo-client/src/common/constants/routes.js
  NangPaGo-client/src/components/page/ErrorGuidePage.jsx
  NangPaGo-client/src/main.jsx
  NangPaGo-client/src/pages/error/LoginExpired.jsx
  NangPaGo-client/src/pages/error/NotFound.jsx
  NangPaGo-client/src/pages/error/UnauthenticatedAccess.jsx
  NangPaGo-client/src/routes/Router.jsx
Labels: bug, refactoring

#262 [NPG-189] 커뮤니티 - 비로그인 상태일 때 댓글, 좋아요 카운트 요청 실패
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/config/security/SecurityConfig.java
  NangPaGo-client/src/api/comment.js
  NangPaGo-client/src/api/commentService.js
  NangPaGo-client/src/common/constants/pagination.js
  NangPaGo-client/src/components/comment/Comment.jsx
  NangPaGo-client/src/components/comment/CommentList.jsx
  NangPaGo-client/src/components/community/Community.jsx
  NangPaGo-client/src/components/recipe/Recipe.jsx
  NangPaGo-client/src/pages/common/DetailPage.jsx
Labels: bug, refactoring

#257 [NPG-201] 관리자 유저 페이지 기능 추가
  NangPaGo-admin/src/api/usermanage.js
  NangPaGo-admin/src/pages/Users.jsx
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/controller/DashboardController.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/service/ChartService.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/controller/UserController.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/dto/UserDto.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/repository/UserRepository.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/service/UserService.java
Labels: enhancement

#258 [NPG-191] 기존 레시피 출처 표기 및 관리자화면 너비 고정
  NangPaGo-admin/src/components/DashboardLayout.jsx
  NangPaGo-client/src/components/recipe/Recipe.jsx
Labels: chore

#263 [NPG-180] 리팩토링 - API 함수명 통일 및 useAuth 훅 분리
  NangPaGo-client/src/api/community.js
  NangPaGo-client/src/api/detailPage.js
  NangPaGo-client/src/api/post.js
  NangPaGo-client/src/api/postStatus.js
  NangPaGo-client/src/api/recipe.js
  NangPaGo-client/src/api/refrigerator.js
  NangPaGo-client/src/components/community/Community.jsx
  NangPaGo-client/src/components/community/CommunityListContent.jsx
  NangPaGo-client/src/components/recipe/Recipe.jsx
  NangPaGo-client/src/components/recipe/RecipeListContent.jsx
  NangPaGo-client/src/hooks/useAuth.js
  NangPaGo-client/src/hooks/usePostStatus.js
  NangPaGo-client/src/hooks/useRecipeSearch.js
  NangPaGo-client/src/hooks/useRefrigerator.js
  NangPaGo-client/src/pages/common/DetailPage.jsx
  NangPaGo-client/src/pages/community/ModifyCommunity.jsx
Labels: refactoring

#264 [NPG-180] 버튼 및 모달 컴포넌트 리팩토링 및 기능 개선
  NangPaGo-client/src/components/button/ToggleButton.jsx
  NangPaGo-client/src/components/comment/Comment.jsx
  NangPaGo-client/src/components/community/Community.jsx
  NangPaGo-client/src/components/modal/LoginModal.jsx
  NangPaGo-client/src/components/recipe/Recipe.jsx
  NangPaGo-client/src/hooks/usePostStatus.js
Labels: enhancement, refactoring

#265 [NPG-210] 유저 조회 - `findById()`로 조회할 수 있게 개선
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/component/auth/AuthenticationHolder.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/community/controller/CommunityCommentController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/community/dto/CommunityCommentResponseDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/community/service/CommunityCommentService.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/comment/community/service/CommunityCommentServiceTest.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/auth/UserDetailsImpl.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/util/web/JwtUtil.java
Labels: refactoring

#266 [NO-ISSUE] Fix: CookingStepsSlider의 ForwardRef 경고 해결
  NangPaGo-client/src/components/recipe/CookingStepsSlider.jsx
Labels: bug

#269 [NPG-190] 레시피 요리과정 슬라이더 버튼 추가
  NangPaGo-client/src/components/recipe/CookingStepsSlider.jsx
Labels: chore

#270 [NPG-210] `findById` 리팩터링 - NPE 방지 및 일부 코드에 적용
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/aop/auth/AuthenticationAspect.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/component/auth/AuthenticationHolder.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/auth/controller/AuthController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/recipe/controller/RecipeCommentController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/recipe/dto/RecipeCommentResponseDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/recipe/repository/RecipeCommentRepository.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/recipe/service/RecipeCommentService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/controller/CommunityController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/dto/CommunityResponseDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/repository/CommunityRepository.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/service/CommunityService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/controller/UserController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/repository/UserRepository.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/service/UserService.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/comment/recipe/service/RecipeCommentServiceTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/community/repository/CommunityRepositoryTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/community/service/CommunityServiceTest.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/user/User.java
Labels: refactoring

#271 [NPG-210] User 인증 로직에서 `findByEmail()` 제거
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/component/auth/AuthenticationHolder.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/auth/service/OAuth2ProviderTokenService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/controller/CommunityLikeController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/repository/CommunityLikeRepository.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/service/CommunityLikeService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/controller/RecipeFavoriteController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/repository/RecipeFavoriteRepository.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/service/RecipeFavoriteService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/controller/RecipeController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/dto/RecipeLikeMessageDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/messaging/LikeNotificationConsumer.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/messaging/LikeNotificationPublisher.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/repository/RecipeLikeRepository.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/service/RecipeLikeMessageService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/service/RecipeLikeService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/refrigerator/controller/RefrigeratorController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/refrigerator/repository/RefrigeratorRepository.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/refrigerator/service/RefrigeratorService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/controller/UserController.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/service/UserService.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/community/service/CommunityLikeServiceTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/favorite/recipe/service/RecipeFavoriteServiceTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/recipe/messaging/LikeNotificationConsumerTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/recipe/repository/RecipeLikeRepositoryTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/recipe/service/RecipeLikeMessageServiceTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/recipe/service/RecipeLikeServiceTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/refrigerator/repository/RefrigeratorRepositoryTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/refrigerator/service/RefrigeratorServiceTest.java
Labels: refactoring

#272 [NO-ISSUE] Vite 관련 보안 경고 해결
  NangPaGo-admin/package-lock.json
  NangPaGo-admin/package.json
  NangPaGo-client/package-lock.json
  NangPaGo-client/package.json
Labels: chore

#267 [NPG-132] 유저 회원탈퇴 및 재가입 기능구현
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/community/dto/CommunityCommentResponseDto.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/recipe/dto/RecipeCommentResponseDto.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/comment/recipe/service/RecipeCommentServiceTest.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/user/User.java
  NangPaGo-client/src/components/comment/CommentList.jsx
  NangPaGo-client/src/hooks/useRefrigerator.js
Labels: chore

#275 [NO-ISSUE] 누락된 테스트 작성 및 관련 코드 리팩터링
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/auth/filter/JwtAuthenticationFilter.java
  NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/component/auth/AuthenticationHolder.java
  NangPaGo-api/NangPaGo-admin/src/test/java/com/mars/admin/auth/filter/JwtAuthenticationFilterTest.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/auth/handler/OAuth2SuccessHandler.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/config/web/HttpClientConfig.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/auth/client/OAuth2ApiClient.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/auth/repository/OAuthProviderTokenRepository.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/auth/service/OAuth2ProviderTokenService.java
  NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/auth/service/TokenService.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/aop/auth/AuthenticationAspectTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/auth/filter/JwtAuthenticationFilterTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/auth/handler/OAuth2SuccessHandlerTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/auth/service/OAuth2LogoutServiceTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/auth/vo/OAuth2RequestResolverTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/auth/service/OAuth2ProviderTokenServiceTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/auth/service/TokenServiceTest.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/provider/TestJwtProvider.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/service/TestService.java
  NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/support/IntegrationTestSupport.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/auth/OAuthProviderToken.java
  NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/user/User.java
Labels: refactoring, test
